export const patternCode = 'template'

export const patternDefinition = {
  code: 'template',
  name: 'Template Method',
  type: 'BEHAVIORAL',
  description: 'Definit le squelette stable d un algorithme puis laisse certaines étapes varier dans les sous-classes.',
  useCase: 'Construire un workflow prepare -> execute -> finalise dans lequel seule l etape centrale change selon le scenario choisi.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_TEMPLATE_METHOD', 'WITHOUT_TEMPLATE_METHOD'],
      defaultValue: 'WITH_TEMPLATE_METHOD',
    },
    {
      name: 'workflowCode',
      label: 'Étape personnalisee',
      type: 'SELECT',
      required: true,
      allowedValues: ['RELEASE_PIPELINE', 'SECURITY_AUDIT', 'DATA_SYNC'],
      defaultValue: 'RELEASE_PIPELINE',
    },
    {
      name: 'workflowName',
      label: 'Nom du workflow',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Workflow Builder',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Le workflow garde sa recette commune pendant que l etape centrale change selon le scenario.',
  intuition:
    "Template Method est utile quand plusieurs processus suivent presque la meme sequence. Au lieu de recopier preparer, finaliser et publier partout, on garde ce canevas dans une classe de base et on specialise seulement l etape qui varie vraiment.",
  readingGuide:
    "Lis d abord le squelette central, puis les trois cartes Prepare / Execute / Finalize. Change ensuite l etape personnalisee pour voir que seule la carte Execute varie alors que le reste du workflow reste stable.",
  studentAngle:
    "Le declic pedagogique est de comprendre que le pattern ne rend pas tout flexible. Il fixe justement l ordre global, puis ouvre de petits points d extension precis.",
  developerAngle:
    "Template Method marche bien pour des jobs batch, des pipelines de traitement, des imports ou des routines de deploiement. Le risque apparait quand on force trop de variations dans l heritage au lieu d extraire une vraie composition.",
  playfulPrompt:
    "Passe en mode sans Template Method pour voir la finalisation devenir fragile, puis compare avec le squelette commun qui garantit prepare -> execute -> finalise.",
  steps: [
    'Le client lance un workflow sur un squelette commun.',
    'La methode template enchaine toujours Prepare, Execute puis Finalize.',
    'La sous-classe specialise seulement Execute selon le scenario choisi.',
    'Le resultat final reste stable sans recopier tout le processus.',
  ],
  glossary: [
    {
      term: 'Methode template',
      definition: 'Methode qui fixe l ordre global de l algorithme.',
    },
    {
      term: 'Hook specialise',
      definition: 'Étape redefinie par une sous-classe pour injecter son comportement variable.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1260 760',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 290,
      width: 246,
      height: 126,
      title: 'WorkflowClient',
      stereotype: 'Client',
      methods: ['+ runWorkflow()', '+ chooseScenario()'],
      tone: 'teal',
    },
    {
      id: 'template',
      x: 404,
      y: 108,
      width: 318,
      height: 208,
      title: 'AbstractWorkflowTemplate',
      stereotype: 'Abstract Class',
      methods: ['+ run()', '# prepare()', '# executeSpecificStep()', '# finalizeRun()'],
      tone: 'accent',
    },
    {
      id: 'release',
      x: 404,
      y: 402,
      width: 278,
      height: 148,
      title: 'ReleaseWorkflow',
      stereotype: 'Concrete Class',
      methods: ['+ executeSpecificStep()'],
      tone: 'sand',
    },
    {
      id: 'audit',
      x: 744,
      y: 402,
      width: 278,
      height: 148,
      title: 'SecurityAuditWorkflow',
      stereotype: 'Concrete Class',
      methods: ['+ executeSpecificStep()'],
      tone: 'teal',
    },
    {
      id: 'sync',
      x: 744,
      y: 592,
      width: 278,
      height: 148,
      title: 'DataSyncWorkflow',
      stereotype: 'Concrete Class',
      methods: ['+ executeSpecificStep()'],
      tone: 'sand',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'template',
      label: 'calls run()',
      marker: 'arrow',
    },
    {
      from: 'release',
      to: 'template',
      label: 'extends',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'audit',
      to: 'template',
      label: 'extends',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'sync',
      to: 'template',
      label: 'extends',
      marker: 'triangle',
      dashed: true,
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'template',
  title: 'Quiz Template Method',
  description: 'Teste ta comprehension d un algorithme stable dont certaines étapes varient.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'template-q1',
      label: 'Le pattern Template Method permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Il fixe le squelette d un algorithme tout en laissant quelques étapes varier.',
      choices: [
        { id: 'skeleton', label: 'Fixer un squelette d algorithme avec quelques étapes variables' },
        { id: 'clone', label: 'Cloner un objet deja configure' },
        { id: 'cache', label: 'Partager un cache global' },
      ],
      correctChoiceIds: ['skeleton'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q2',
      label: 'Dans Template Method, l ordre global des étapes est defini par la classe de base.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : la methode template garde la sequence stable.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q3',
      label: 'Template Method appartient a la famille :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Template Method est un pattern comportemental.',
      choices: [
        { id: 'creational', label: 'Création' },
        { id: 'structural', label: 'Structurel' },
        { id: 'behavioral', label: 'Comportemental' },
      ],
      correctChoiceIds: ['behavioral'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q4',
      label: 'Quelle partie varie generalement selon la sous-classe ?',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Les sous-classes implementent surtout les étapes specialisees ou hooks.',
      choices: [
        { id: 'hook', label: 'Une etape specialisee comme execute()' },
        { id: 'registry', label: 'Le registre global des patterns' },
        { id: 'database', label: 'La base de donnees' },
      ],
      correctChoiceIds: ['hook'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q5',
      label: 'Associe chaque etape au bon role dans un workflow Template Method.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Prepare met en place, Execute specialise le travail et Finalize cloture le flux.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'prepare', label: 'Prepare' },
        { id: 'execute', label: 'Execute' },
        { id: 'finalize', label: 'Finalize' },
      ],
      rightItems: [
        { id: 'setup', label: 'Met en place le contexte' },
        { id: 'custom', label: 'Realise l etape variable' },
        { id: 'cleanup', label: 'Cloture et publie l etat final' },
      ],
      correctPairs: [
        { leftId: 'prepare', rightId: 'setup' },
        { leftId: 'execute', rightId: 'custom' },
        { leftId: 'finalize', rightId: 'cleanup' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q6',
      label: 'Template Method evite surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le pattern evite de recopier les memes étapes communes dans plusieurs workflows.',
      choices: [
        { id: 'duplication', label: 'La duplication du workflow commun' },
        { id: 'events', label: 'Les evenements pub/sub' },
        { id: 'memory', label: 'La duplication memoire' },
      ],
      correctChoiceIds: ['duplication'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q7',
      label: 'Une sous-classe devrait librement changer l ordre de la methode template sans toucher la classe de base.',
      type: 'TRUE_FALSE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Non : si l ordre change, c est justement le squelette stable qui n existe plus vraiment.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['false'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q8',
      label: 'Quel cas illustre bien Template Method ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Un pipeline prepare -> execute -> finalise avec un centre variable est un tres bon exemple.',
      choices: [
        { id: 'workflow', label: 'Un workflow stable avec une etape centrale specialisee' },
        { id: 'singleton', label: 'Un service unique global' },
        { id: 'adapter', label: 'Une conversion d interface' },
      ],
      correctChoiceIds: ['workflow'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q9',
      label: 'Le coeur du pattern est la combinaison :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le pattern melange invariants communs et points d extension limites.',
      choices: [
        { id: 'fixed-plus-variation', label: 'Squelette fixe + variations controlees' },
        { id: 'cache-plus-lock', label: 'Cache + verrou global' },
        { id: 'observer-plus-event', label: 'Observers + evenement' },
      ],
      correctChoiceIds: ['fixed-plus-variation'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'template-q10',
      label: 'Remets la sequence Template Method dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'La preparation ouvre le workflow, execute specialise le coeur, puis finalize cloture.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'prepare', label: 'Preparer le contexte' },
        { id: 'execute', label: 'Executer l etape specialisee' },
        { id: 'finalize', label: 'Finaliser le workflow' },
        { id: 'result', label: 'Publier le resultat' },
      ],
      correctOrder: ['prepare', 'execute', 'finalize', 'result'],
    },
  ],
}
