export const patternCode = 'facade'

export const patternDefinition = {
  code: 'facade',
  name: 'Facade',
  type: 'STRUCTURAL',
  description: 'Expose une entree simple vers plusieurs sous-systemes et masque la choregraphie detaillee.',
  useCase: 'Lancer une routine domotique audio + lumiere + securite en un clic au lieu de piloter chaque module manuellement.',
  complexityLevel: 'BEGINNER',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_FACADE', 'WITHOUT_FACADE'],
      defaultValue: 'WITH_FACADE',
    },
    {
      name: 'routineCode',
      label: 'Routine',
      type: 'SELECT',
      required: true,
      allowedValues: ['CINEMA_MODE', 'NIGHT_SHUTDOWN', 'PARTY_STARTUP'],
      defaultValue: 'CINEMA_MODE',
    },
    {
      name: 'triggerLabel',
      label: 'Libellé du bouton',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Start',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Une seule entree pilote un systeme complet sans exposer toute sa tuyauterie au client.',
  intuition:
    "Facade ne remplace pas les sous-systemes. Elle leur met simplement une facade lisible devant, pour qu un client declenche une routine sans memoriser chaque appel technique.",
  readingGuide:
    "Lis d abord le bouton de depart, puis suis le hub Facade vers audio, lumiere et securite. Compare ensuite avec le mode sans Facade pour voir le flux plus disperse.",
  studentAngle:
    "Le declic pedagogique est de voir qu on simplifie l usage, pas qu on fait disparaitre la complexite interne.",
  developerAngle:
    "Facade devient utile quand plusieurs services doivent etre appeles dans un ordre stable et que tu veux eviter de propager cette choregraphie partout dans le code client.",
  playfulPrompt:
    "Teste Cinema Mode et Party Startup, puis repasse en mode sans Facade pour voir quel sous-systeme se perd quand le client doit tout faire lui-meme.",
  steps: [
    'Le client declenche une routine via une entree unique.',
    'La facade traduit cette intention en appels coordonnes.',
    'Les sous-systemes audio, lumiere et securite executent chacun leur partie.',
    'Le client recupere un etat global simple au lieu de gerer chaque detail.',
  ],
  glossary: [
    {
      term: 'Facade',
      definition: 'Point d entree simplifie qui masque une choregraphie interne plus complexe.',
    },
    {
      term: 'Sous-systeme',
      definition: 'Module specialise qui continue a exister derriere la facade et fait le vrai travail.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1220 700',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 246,
      width: 250,
      height: 136,
      title: 'HomeAutomationClient',
      stereotype: 'Client',
      methods: ['+ pressStart()', '+ chooseRoutine()'],
      tone: 'teal',
    },
    {
      id: 'facade',
      x: 404,
      y: 220,
      width: 290,
      height: 172,
      title: 'SmartHomeFacade',
      stereotype: 'Facade',
      fields: ['- audio: AudioSystem', '- light: LightSystem', '- security: SecuritySystem'],
      methods: ['+ startRoutine(routine)', '+ shutdownNight()'],
      tone: 'accent',
    },
    {
      id: 'audio',
      x: 830,
      y: 82,
      width: 250,
      height: 124,
      title: 'AudioSystem',
      stereotype: 'Subsystem',
      methods: ['+ activatePreset()', '+ standby()'],
      tone: 'teal',
    },
    {
      id: 'light',
      x: 830,
      y: 276,
      width: 250,
      height: 124,
      title: 'LightSystem',
      stereotype: 'Subsystem',
      methods: ['+ applyScene()', '+ dimAll()'],
      tone: 'sand',
    },
    {
      id: 'security',
      x: 830,
      y: 470,
      width: 250,
      height: 124,
      title: 'SecuritySystem',
      stereotype: 'Subsystem',
      methods: ['+ armNight()', '+ enableGuestAccess()'],
      tone: 'teal',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'facade',
      label: 'uses',
      marker: 'arrow',
    },
    {
      from: 'facade',
      to: 'audio',
      label: 'orchestrates',
      marker: 'diamond',
    },
    {
      from: 'facade',
      to: 'light',
      label: 'orchestrates',
      marker: 'diamond',
    },
    {
      from: 'facade',
      to: 'security',
      label: 'orchestrates',
      marker: 'diamond',
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'facade',
  title: 'Quiz Facade',
  description: 'Teste ta comprehension de la simplification d un systeme complexe par une entree unique.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'facade-q1',
      label: 'Le pattern Facade sert surtout a :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Facade expose une API simple devant plusieurs sous-systemes.',
      choices: [
        { id: 'simplify', label: 'Simplifier l acces a un systeme complexe' },
        { id: 'clone', label: 'Cloner un objet' },
        { id: 'notify', label: 'Notifier des abonnes' },
      ],
      correctChoiceIds: ['simplify'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q2',
      label: 'Facade supprime les sous-systemes internes.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Non : les sous-systemes existent toujours, mais on les masque derriere une interface plus simple.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['false'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q3',
      label: 'Facade appartient a la famille :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Facade est un pattern structurel.',
      choices: [
        { id: 'creational', label: 'Création' },
        { id: 'structural', label: 'Structurel' },
        { id: 'behavioral', label: 'Comportemental' },
      ],
      correctChoiceIds: ['structural'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q4',
      label: 'Le client parle idealement a :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client depend de la facade simplifiee plutot que de tous les modules internes.',
      choices: [
        { id: 'facade', label: 'Une interface Facade' },
        { id: 'all', label: 'Tous les sous-systemes directement' },
        { id: 'db', label: 'La base de donnees' },
      ],
      correctChoiceIds: ['facade'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q5',
      label: 'Associe chaque role Facade a sa responsabilite.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client declenche, la facade orchestre et les sous-systemes executent.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'client', label: 'Client' },
        { id: 'facade', label: 'Facade' },
        { id: 'subsystems', label: 'Sous-systemes' },
      ],
      rightItems: [
        { id: 'trigger', label: 'Declenche la demande' },
        { id: 'orchestrate', label: 'Coordonne plusieurs appels' },
        { id: 'execute', label: 'Executent le vrai travail' },
      ],
      correctPairs: [
        { leftId: 'client', rightId: 'trigger' },
        { leftId: 'facade', rightId: 'orchestrate' },
        { leftId: 'subsystems', rightId: 'execute' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q6',
      label: 'Quel exemple illustre bien Facade ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Un bouton unique qui demarre audio, lumiere et securite est un exemple clair de Facade.',
      choices: [
        { id: 'home', label: 'Un bouton Start qui orchestre plusieurs modules' },
        { id: 'flyweight', label: 'Partager la memoire entre objets' },
        { id: 'state', label: 'Changer d etat a runtime' },
      ],
      correctChoiceIds: ['home'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q7',
      label: 'Facade peut reduire le couplage du client avec les details internes.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Oui : le client depend d une entree plus simple au lieu de connaitre chaque sous-systeme concret.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q8',
      label: 'Facade evite surtout au client :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client n a plus besoin de memoriser l ordre de plusieurs appels techniques.',
      choices: [
        { id: 'orchestration', label: 'Une orchestration manuelle verbeuse' },
        { id: 'memory', label: 'La duplication memoire' },
        { id: 'events', label: 'Les evenements pub/sub' },
      ],
      correctChoiceIds: ['orchestration'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q9',
      label: 'Facade cache surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le pattern masque la complexite d utilisation du systeme, pas forcement toute son implementation interne.',
      choices: [
        { id: 'complexity', label: 'La complexite d utilisation du systeme' },
        { id: 'database', label: 'La base de donnees uniquement' },
        { id: 'inheritance', label: 'L heritage multiple' },
      ],
      correctChoiceIds: ['complexity'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'facade-q10',
      label: 'Remets la boucle Facade dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client appelle la facade, la facade orchestre, les sous-systemes executent, puis l etat global revient.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'call', label: 'Le client appelle la facade' },
        { id: 'dispatch', label: 'La facade distribue les appels' },
        { id: 'subsystems', label: 'Les sous-systemes executent' },
        { id: 'result', label: 'Le resultat global revient au client' },
      ],
      correctOrder: ['call', 'dispatch', 'subsystems', 'result'],
    },
  ],
}
