export const defaultPatternCode = 'strategy'

export const fallbackPatterns = [
  {
    code: 'abstract-factory',
    name: 'Abstract Factory',
    type: 'CREATIONAL',
    description: 'Fabrique des familles d’objets cohérentes sans exposer les classes concrètes ni mélanger les thèmes au niveau du client.',
    useCase: 'Choisir un thème sci-fi ou médiéval puis générer un héros, un transport et une relique parfaitement alignés.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'bridge',
    name: 'Bridge',
    type: 'STRUCTURAL',
    description: 'Sépare une abstraction de son implémentation pour les faire varier indépendamment sans explosion de sous-classes.',
    useCase: 'Piloter la même forme avec plusieurs moteurs de rendu comme Shape + RenderEngine dans une UI ou un moteur graphique.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'memento',
    name: 'Memento',
    type: 'BEHAVIORAL',
    description: 'Capture et restaure un état interne sans exposer directement les détails de cet état au client.',
    useCase: 'Sauvegarder une scène, appliquer des mutations risquées puis restaurer proprement un checkpoint comme dans un jeu ou un éditeur.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'iterator',
    name: 'Iterator',
    type: 'BEHAVIORAL',
    description: 'Expose un parcours séquentiel sur une collection sans révéler sa structure interne ni dupliquer la logique de navigation.',
    useCase: 'Parcourir une liste ou un arbre avec un curseur next / previous stable, même quand la structure sous-jacente change.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'template',
    name: 'Template Method',
    type: 'BEHAVIORAL',
    description: "Définit le squelette stable d'un algorithme puis laisse certaines étapes varier dans les sous-classes.",
    useCase: "Construire un workflow préparé -> exécuté -> finalisé dans lequel seule l'étape centrale change selon le scénario choisi.",
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'interpreter',
    name: 'Interpreter',
    type: 'BEHAVIORAL',
    description: 'Interprète un mini langage en transformant chaque instruction en expression exécutable sur un contexte.',
    useCase: 'Écrire un script MOVE / TURN / ATTACK / REPEAT puis visualiser son parsing, son exécution et ses limites sans interprète complet.',
    complexityLevel: 'ADVANCED',
  },
  {
    code: 'visitor',
    name: 'Visitor',
    type: 'BEHAVIORAL',
    description: 'Ajoute des opérations sur une structure existante sans modifier les classes des éléments parcourus.',
    useCase: 'Analyser un arbre de dossiers et de fichiers avec plusieurs visiteurs : compter, valoriser, rechercher ou scanner.',
    complexityLevel: 'ADVANCED',
  },
  {
    code: 'prototype',
    name: 'Prototype',
    type: 'CREATIONAL',
    description: 'Duplique un objet déjà configuré pour créer rapidement de nouvelles variantes sans repasser par toute la construction.',
    useCase: 'Cloner un robot, un drone ou un avatar puis observer la différence entre copie superficielle et copie profonde.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'mediator',
    name: 'Mediator',
    type: 'BEHAVIORAL',
    description: "Centralise les échanges entre plusieurs objets pour qu'ils passent par un hub commun au lieu de se connaître tous directement.",
    useCase: 'Construire un chat multijoueur où les messages transitent par un salon central pour réduire le couplage entre participants.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'chain',
    name: 'Chain of Responsibility',
    type: 'BEHAVIORAL',
    description: 'Fait circuler une requête dans une chaîne de handlers capables de la laisser passer, de la bloquer ou de la traiter.',
    useCase: 'Visualiser un pipeline auth -> validation -> traitement où chaque maillon prend une décision locale sans gros controller central.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'command',
    name: 'Command',
    type: 'BEHAVIORAL',
    description: "Encapsule une action dans un objet pour pouvoir la déclencher, l'historiser, l'annuler et la rejouer sans coupler l'interface au receiver.",
    useCase: "Construire un simulateur undo / redo, un éditeur ou un mini jeu d'actions historisées avec piles de commandes.",
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'adapter',
    name: 'Adapter',
    type: 'STRUCTURAL',
    description: 'Traduit une interface incompatible vers le contrat attendu par le client sans modifier le composant legacy.',
    useCase: 'Connecter une source historique à une cible moderne en convertissant connecteur, protocole ou format de message.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'proxy',
    name: 'Proxy',
    type: 'STRUCTURAL',
    description: "Place un intermédiaire devant une ressource pour contrôler l'accès, retarder son chargement ou masquer sa nature réelle.",
    useCase: "Filtrer l'accès à une ressource sensible, cacher un appel réseau lourd ou activer un lazy loading avant la vraie ressource.",
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'facade',
    name: 'Facade',
    type: 'STRUCTURAL',
    description: 'Expose une entrée simple vers plusieurs sous-systèmes et masque la chorégraphie détaillée.',
    useCase: 'Déclencher une routine domotique audio + lumière + sécurité en un clic au lieu de piloter chaque module manuellement.',
    complexityLevel: 'BEGINNER',
  },
  {
    code: 'composite',
    name: 'Composite',
    type: 'STRUCTURAL',
    description: "Compose des objets en arbre pour traiter uniformément un élément simple et un groupe d'éléments.",
    useCase: 'Construire un explorateur de dossiers et fichiers où une action appliquée au root descend naturellement sur toute la structure.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'builder',
    name: 'Builder',
    type: 'CREATIONAL',
    description: 'Construit un objet complexe étape par étape au lieu de pousser une longue liste de paramètres dans un constructeur géant.',
    useCase: 'Assembler visuellement une voiture, un personnage ou une maison en posant structure, noyau, module et finition dans un ordre lisible.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'singleton',
    name: 'Singleton',
    type: 'CREATIONAL',
    description: "Garantit qu'un service central ne possède qu'une seule instance partagée dans toute l'application.",
    useCase: 'Partager la même configuration globale, le même logger ou le même gestionnaire audio entre plusieurs clients.',
    complexityLevel: 'BEGINNER',
  },
  {
    code: 'state',
    name: 'State',
    type: 'BEHAVIORAL',
    description: "Fait varier le comportement d'un contexte selon son état interne sans multiplier les conditions dans le code client.",
    useCase: 'Piloter une machine à états de personnage, un workflow ou un cycle de vie UI avec des transitions explicites.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'flyweight',
    name: 'Flyweight',
    type: 'STRUCTURAL',
    description: "Partage l'état intrinsèque entre de nombreux objets pour éviter de multiplier les instances lourdes en mémoire.",
    useCase: "Afficher des milliers d'arbres, particules ou projectiles en mutualisant textures, meshes et autres données communes.",
    complexityLevel: 'ADVANCED',
  },
  {
    code: 'decorator',
    name: 'Decorator',
    type: 'STRUCTURAL',
    description: "Ajoute des comportements à un objet en l'enveloppant avec des couches successives, sans modifier sa classe d'origine.",
    useCase: 'Empiler des power-ups sur un personnage, enrichir un café customisable ou combiner des effets sans explosion de classes.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'factory',
    name: 'Factory Method',
    type: 'CREATIONAL',
    description: "Centralise la création d'objets derrière une fabrique spécialisée.",
    useCase: 'Choisir dynamiquement le bon type de véhicule sans dupliquer des constructeurs.',
    complexityLevel: 'BEGINNER',
  },
  {
    code: 'observer',
    name: 'Observer',
    type: 'BEHAVIORAL',
    description: 'Relie un sujet à plusieurs abonnés qui reçoivent automatiquement chaque notification.',
    useCase: 'Propager un événement de publication à plusieurs consommateurs sans les coupler entre eux.',
    complexityLevel: 'INTERMEDIATE',
  },
  {
    code: 'strategy',
    name: 'Strategy',
    type: 'BEHAVIORAL',
    description: "Permet de changer un algorithme à l'exécution sans modifier le contexte.",
    useCase: 'Basculer entre plusieurs modes de paiement dans un même workflow.',
    complexityLevel: 'INTERMEDIATE',
  },
]

export const fallbackPatternsByCode = Object.fromEntries(
  fallbackPatterns.map((pattern) => [pattern.code, pattern]),
)

export const patternPreviewTaglinesByCode = {
  'abstract-factory': "Un thème unique crée toute une famille d'objets cohérents d'un seul coup.",
  adapter: 'Une interface legacy entre, une interface compatible ressort.',
  builder: "L'objet se construit pièce par pièce avant la livraison finale.",
  bridge: 'La forme reste stable pendant que le moteur de rendu change librement.',
  chain: "La requête traverse la chaîne jusqu'à être acceptée ou stoppée.",
  command: 'Chaque action devient un objet rejouable avec undo et redo.',
  composite: "Un root, des dossiers et des fichiers répondent au même contrat dans tout l'arbre.",
  decorator: "Les comportements s'empilent comme des couches autour du composant.",
  facade: 'Un seul bouton orchestre plusieurs sous-systèmes et cache la chorégraphie.',
  factory: "La création est déléguée à une fabrique au lieu d'être dispersée.",
  flyweight: "Des milliers d'objets partagent le même état intrinsèque.",
  interpreter: "Le script devient un arbre d'expressions qui pilote la mission.",
  iterator: 'Le curseur avance et recule sans exposer la structure réelle de la collection.',
  memento: 'Les savepoints capturent un état complet avant un rewind exact ou partiel.',
  mediator: 'Les échanges passent par un hub central plutôt que par du couplage direct.',
  observer: 'Un sujet diffuse un événement, plusieurs abonnés réagissent.',
  prototype: 'Un blueprint source génère des clones qui partagent ou non leur état profond.',
  proxy: 'Une ressource reste derrière un gardien qui autorise, bloque ou charge plus tard.',
  singleton: 'Tous les clients pointent vers la même instance partagée.',
  state: 'Le contexte change de comportement quand son état évolue.',
  strategy: "Le contexte reste stable pendant que l'algorithme change.",
  template: "Le squelette du workflow reste fixe pendant que l'étape Execute varie.",
  visitor: 'Le même arbre accueille plusieurs analyses sans modifier les classes des nœuds.',
}

export const specializedScenePatternCodes = [
  'abstract-factory',
  'adapter',
  'builder',
  'bridge',
  'chain',
  'command',
  'composite',
  'decorator',
  'facade',
  'flyweight',
  'interpreter',
  'iterator',
  'memento',
  'mediator',
  'prototype',
  'proxy',
  'singleton',
  'state',
  'template',
  'visitor',
]

export function getPatternPreviewTagline(code) {
  return patternPreviewTaglinesByCode[code] ?? null
}

export function hasSpecializedPatternScene(code) {
  return specializedScenePatternCodes.includes(code)
}
