export const patternCode = 'proxy'

export const patternDefinition = {
  code: 'proxy',
  name: 'Proxy',
  type: 'STRUCTURAL',
  description: 'Place un intermediaire devant une ressource pour controler l acces, retarder son chargement ou masquer sa nature reelle.',
  useCase: 'Filtrer l acces a une ressource sensible, cacher un appel reseau lourd ou activer un lazy loading avant la vraie ressource.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_PROXY', 'WITHOUT_PROXY'],
      defaultValue: 'WITH_PROXY',
    },
    {
      name: 'requestLabel',
      label: 'Nom de la requete',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Open premium vault',
    },
    {
      name: 'requesterRole',
      label: 'Role demandeur',
      type: 'SELECT',
      required: true,
      allowedValues: ['ADMIN', 'MEMBER', 'GUEST'],
      defaultValue: 'GUEST',
    },
    {
      name: 'resourceCode',
      label: 'Ressource cible',
      type: 'SELECT',
      required: true,
      allowedValues: ['VAULT_VIDEO', 'REPORT_ARCHIVE', 'LIVE_DASHBOARD'],
      defaultValue: 'VAULT_VIDEO',
    },
    {
      name: 'cacheState',
      label: 'Etat du cache',
      type: 'SELECT',
      required: true,
      allowedValues: ['COLD', 'WARM'],
      defaultValue: 'COLD',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'La ressource reelle reste derriere un gardien qui peut autoriser, bloquer ou retarder le chargement.',
  intuition:
    "Proxy garde le meme contrat que la vraie ressource, mais ajoute un pouvoir de mediation. C est la que naissent le controle d acces, le lazy loading et la simulation d acces reseau.",
  readingGuide:
    "Observe d abord le trajet de la requete entre client, proxy et real subject. Puis compare le verdict, le cache et la timeline pour voir si la charge lourde part ou reste bloquee.",
  studentAngle:
    "Le declic pedagogique est de voir qu on n appelle pas toujours la vraie ressource. Souvent, on parle d abord a un representant qui decide quoi faire.",
  developerAngle:
    "Proxy devient utile pour filtrer les acces, repousser un chargement couteux, masquer un service distant ou instrumenter un point d entree sensible.",
  playfulPrompt:
    "Teste un guest sur une archive admin-only, puis passe en mode sans proxy pour voir ce qui change quand la garde disparait.",
  steps: [
    'Le client emet une requete vers le contrat du sujet.',
    'Le proxy controle le role, le cache ou le besoin de chargement.',
    'La ressource reelle n est appelee que si le proxy le permet.',
    'La reponse revient au client avec ou sans mediation visible.',
  ],
  glossary: [
    {
      term: 'Real Subject',
      definition: 'La ressource concrete qui porte vraiment les donnees ou le travail couteux.',
    },
    {
      term: 'Lazy loading',
      definition: 'Le chargement est differe jusqu au moment exact ou la ressource est reellement necessaire.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1180 700',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 248,
      width: 248,
      height: 132,
      title: 'AccessClient',
      stereotype: 'Client',
      methods: ['+ requestAccess()', '+ render()'],
      tone: 'teal',
    },
    {
      id: 'subject',
      x: 428,
      y: 74,
      width: 272,
      height: 122,
      title: 'ProtectedResource',
      stereotype: 'Subject',
      methods: ['+ open(request): ResourcePayload'],
      tone: 'sand',
    },
    {
      id: 'proxy',
      x: 428,
      y: 282,
      width: 300,
      height: 184,
      title: 'AccessProxy',
      stereotype: 'Proxy',
      fields: ['- realSubject: ProtectedResource', '- cache: ResourcePayload?'],
      methods: ['+ open(request)', '+ checkAccess()', '+ lazyLoad()'],
      tone: 'accent',
    },
    {
      id: 'real',
      x: 840,
      y: 282,
      width: 254,
      height: 156,
      title: 'RealProtectedResource',
      stereotype: 'Real Subject',
      methods: ['+ loadPayload()', '+ open(request)'],
      tone: 'teal',
    },
    {
      id: 'payload',
      x: 838,
      y: 92,
      width: 258,
      height: 120,
      title: 'ResourcePayload',
      stereotype: 'Payload',
      fields: ['+ status: String', '+ weightMb: int'],
      tone: 'accent',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'subject',
      label: 'depends on',
      marker: 'arrow',
    },
    {
      from: 'proxy',
      to: 'subject',
      label: 'implements',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'proxy',
      to: 'real',
      label: 'guards',
      marker: 'diamond',
    },
    {
      from: 'real',
      to: 'payload',
      label: 'loads',
      marker: 'arrow',
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'proxy',
  title: 'Quiz Proxy',
  description: 'Teste ta comprehension du controle d acces, du lazy loading et du role d intermediaire du Proxy.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'proxy-q1',
      label: 'Le pattern Proxy permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Proxy place un intermediaire devant une ressource pour controler, filtrer ou retarder l acces.',
      choices: [
        { id: 'access', label: 'Controler l acces a une ressource' },
        { id: 'notify', label: 'Notifier des abonnes' },
        { id: 'clone', label: 'Cloner un objet' },
      ],
      correctChoiceIds: ['access'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q2',
      label: 'Proxy appartient a la famille des patterns structurels.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : Proxy est un pattern structurel.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q3',
      label: 'Le proxy et la ressource reelle exposent idealement :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client parle au meme contrat que la ressource reelle, sinon le remplacement devient visible.',
      choices: [
        { id: 'same', label: 'Le meme contrat' },
        { id: 'db', label: 'La meme base de donnees' },
        { id: 'none', label: 'Aucune interface' },
      ],
      correctChoiceIds: ['same'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q4',
      label: 'Quel cas illustre bien Proxy ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Controler l acces a un flux video premium ou retarder son chargement est un bon exemple de Proxy.',
      choices: [
        { id: 'video', label: 'Filtrer l acces a une ressource premium' },
        { id: 'payment', label: 'Changer d algorithme de paiement' },
        { id: 'observer', label: 'Diffuser un evenement' },
      ],
      correctChoiceIds: ['video'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q5',
      label: 'Associe chaque role a sa responsabilite.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client demande, le proxy filtre ou charge, le real subject fait le vrai travail.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'client', label: 'Client' },
        { id: 'proxy', label: 'Proxy' },
        { id: 'subject', label: 'Real Subject' },
      ],
      rightItems: [
        { id: 'request', label: 'Demande l acces' },
        { id: 'filter', label: 'Filtre ou retarde l acces' },
        { id: 'work', label: 'Porte la vraie ressource' },
      ],
      correctPairs: [
        { leftId: 'client', rightId: 'request' },
        { leftId: 'proxy', rightId: 'filter' },
        { leftId: 'subject', rightId: 'work' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q6',
      label: 'Un proxy peut servir a faire du lazy loading.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : le proxy peut differer le vrai chargement jusqu au moment ou la ressource est reellement demandee.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q7',
      label: 'Sans proxy, un probleme classique est :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Sans proxy, l acces direct peut lancer des chargements lourds trop tot ou exposer une ressource sensible.',
      choices: [
        { id: 'eager', label: 'Un acces direct sans garde ni mediation' },
        { id: 'share', label: 'Le partage d etat intrinseque' },
        { id: 'build', label: 'Un constructeur geant' },
      ],
      correctChoiceIds: ['eager'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q8',
      label: 'Le proxy distant, de protection ou virtuel partage un principe commun :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Tous restent une facade remplacable devant le vrai sujet.',
      choices: [
        { id: 'middle', label: 'Interposer un representant devant la vraie ressource' },
        { id: 'switch', label: 'Remplacer des if / else' },
        { id: 'history', label: 'Historiser des commandes' },
      ],
      correctChoiceIds: ['middle'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q9',
      label: 'Le client depend idealement de :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Il depend du contrat du sujet, pas du proxy concret ni du real subject concret.',
      choices: [
        { id: 'contract', label: 'L interface commune du sujet' },
        { id: 'proxy', label: 'La classe Proxy concrete' },
        { id: 'real', label: 'La classe RealSubject concrete' },
      ],
      correctChoiceIds: ['contract'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'proxy-q10',
      label: 'Remets le flux Proxy dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client demande, le proxy controle ou charge, le real subject est contacte si besoin, puis la reponse revient.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'request', label: 'Le client demande la ressource' },
        { id: 'gate', label: 'Le proxy controle l acces' },
        { id: 'subject', label: 'Le vrai sujet est contacte si necessaire' },
        { id: 'return', label: 'La reponse revient au client' },
      ],
      correctOrder: ['request', 'gate', 'subject', 'return'],
    },
  ],
}
