export const patternCode = 'bridge'

export const patternDefinition = {
  code: 'bridge',
  name: 'Bridge',
  type: 'STRUCTURAL',
  description: 'Separe une abstraction de son implementation pour les faire varier independamment sans explosion de sous-classes.',
  useCase: 'Piloter la meme forme avec plusieurs moteurs de rendu comme Shape + RenderEngine dans une UI ou un moteur graphique.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_BRIDGE', 'WITHOUT_BRIDGE'],
      defaultValue: 'WITH_BRIDGE',
    },
    {
      name: 'shapeCode',
      label: 'Abstraction',
      type: 'SELECT',
      required: true,
      allowedValues: ['CIRCLE', 'TRIANGLE', 'BANNER'],
      defaultValue: 'CIRCLE',
    },
    {
      name: 'renderCode',
      label: 'Implementation',
      type: 'SELECT',
      required: true,
      allowedValues: ['VECTOR_ENGINE', 'PIXEL_ENGINE', 'GLOW_ENGINE'],
      defaultValue: 'VECTOR_ENGINE',
    },
    {
      name: 'objectName',
      label: 'Nom de l objet',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Switch Engine',
    },
  ],
}

export const patternLearningContent = {
  strapline:
    'La forme garde son abstraction pendant que le moteur de rendu change librement derrière elle.',
  intuition:
    'Bridge sert quand deux dimensions varient en meme temps. Ici, la forme varie d un cote et le moteur de rendu de l autre. Au lieu de creer une classe par combinaison, on les relie par delegation.',
  readingGuide:
    'Regarde d abord la forme sélectionnée, puis le moteur choisi. La scene montre ensuite si la liaison passe par un vrai pont runtime ou par une sous-classe concrete fusionnee.',
  studentAngle:
    'Le vrai declic est de voir que Bridge ne rend pas tout abstrait pour le plaisir. Il decoupe deux axes de variation qui evoluent independamment.',
  developerAngle:
    'Le pattern est utile pour un moteur graphique, une UI multiplateforme, des drivers, des canaux de sortie ou tout systeme ou abstraction et implementation bougent a des rythmes differents.',
  playfulPrompt:
    'Change la forme et le moteur pour voir comment Bridge garde les memes operations haut niveau tout en changeant completement le rendu concret.',
  steps: [
    'Le client parle a une abstraction stable.',
    'L abstraction delegue la partie concrete a une implementation.',
    'Le moteur concret realise le rendu selon son style.',
    'Changer l implementation ne casse pas la forme ni le client.',
  ],
  glossary: [
    {
      term: 'Abstraction',
      definition: 'Objet haut niveau expose au client, ici la forme.',
    },
    {
      term: 'Implementation',
      definition: 'Objet qui realise le travail concret, ici le moteur de rendu.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1180 720',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 286,
      width: 226,
      height: 118,
      title: 'RenderClient',
      stereotype: 'Client',
      methods: ['+ show(shape)', '+ switchEngine()'],
      tone: 'teal',
    },
    {
      id: 'shape',
      x: 376,
      y: 126,
      width: 300,
      height: 180,
      title: 'Shape',
      stereotype: 'Abstraction',
      fields: ['- engine: RenderEngine'],
      methods: ['+ render()', '+ resize()'],
      tone: 'accent',
    },
    {
      id: 'engine',
      x: 800,
      y: 126,
      width: 254,
      height: 138,
      title: 'RenderEngine',
      stereotype: 'Implementation',
      methods: ['+ drawShape(shape)'],
      tone: 'sand',
    },
    {
      id: 'circle',
      x: 330,
      y: 444,
      width: 210,
      height: 118,
      title: 'CircleShape',
      stereotype: 'Refined Abstraction',
      methods: ['+ render()'],
      tone: 'teal',
    },
    {
      id: 'triangle',
      x: 584,
      y: 444,
      width: 220,
      height: 118,
      title: 'TriangleShape',
      stereotype: 'Refined Abstraction',
      methods: ['+ render()'],
      tone: 'teal',
    },
    {
      id: 'vector',
      x: 826,
      y: 408,
      width: 230,
      height: 118,
      title: 'VectorRenderEngine',
      stereotype: 'Concrete Impl',
      methods: ['+ drawShape(shape)'],
      tone: 'accent',
    },
    {
      id: 'glow',
      x: 826,
      y: 566,
      width: 230,
      height: 118,
      title: 'GlowRenderEngine',
      stereotype: 'Concrete Impl',
      methods: ['+ drawShape(shape)'],
      tone: 'accent',
    },
  ],
  relations: [
    { from: 'client', to: 'shape', label: 'uses', marker: 'arrow' },
    { from: 'shape', to: 'engine', label: 'delegates to', marker: 'diamond' },
    { from: 'circle', to: 'shape', label: 'extends', marker: 'triangle', dashed: true },
    { from: 'triangle', to: 'shape', label: 'extends', marker: 'triangle', dashed: true },
    { from: 'vector', to: 'engine', label: 'implements', marker: 'triangle', dashed: true },
    { from: 'glow', to: 'engine', label: 'implements', marker: 'triangle', dashed: true },
  ],
}

export const fallbackQuiz = {
  patternCode: 'bridge',
  title: 'Quiz Bridge',
  description: 'Teste ta comprehension de la separation abstraction / implementation.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'bridge-q1',
      label: 'Le pattern Bridge permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Bridge separe abstraction et implementation pour les faire varier independamment.',
      choices: [
        { id: 'separate', label: 'Separer abstraction et implementation' },
        { id: 'notify', label: 'Notifier plusieurs observers' },
        { id: 'clone', label: 'Cloner un objet' },
      ],
      correctChoiceIds: ['separate'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q2',
      label: 'Bridge appartient aux patterns structurels.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : il reorganise les relations entre abstraction et implementation.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q3',
      label: 'Dans l exemple Shape + RenderEngine, Shape represente :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Shape est l abstraction qui delegue le detail du rendu.',
      choices: [
        { id: 'abstraction', label: 'L abstraction' },
        { id: 'implementation', label: 'L implementation concrete' },
        { id: 'caretaker', label: 'Le caretaker' },
      ],
      correctChoiceIds: ['abstraction'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q4',
      label: 'Bridge evite surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Il evite l explosion de sous-classes quand deux dimensions varient en meme temps.',
      choices: [
        { id: 'explosion', label: 'L explosion de sous-classes concretes' },
        { id: 'memory', label: 'Le partage memoire' },
        { id: 'undo', label: 'La perte de snapshots' },
      ],
      correctChoiceIds: ['explosion'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q5',
      label: 'Associe chaque element du pattern Bridge a son role.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client appelle, l abstraction delegue et l implementation rend concretement.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'client', label: 'Client' },
        { id: 'abstraction', label: 'Abstraction' },
        { id: 'implementation', label: 'Implementation' },
      ],
      rightItems: [
        { id: 'call', label: 'Declenche render()' },
        { id: 'delegate', label: 'Delegue vers le moteur' },
        { id: 'draw', label: 'Fournit le rendu concret' },
      ],
      correctPairs: [
        { leftId: 'client', rightId: 'call' },
        { leftId: 'abstraction', rightId: 'delegate' },
        { leftId: 'implementation', rightId: 'draw' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q6',
      label: 'Quel duo illustre bien Bridge ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Shape + RenderEngine est l exemple classique.',
      choices: [
        { id: 'shape-engine', label: 'Shape + RenderEngine' },
        { id: 'subject-observer', label: 'Subject + Observer' },
        { id: 'factory-product', label: 'Factory + Product' },
      ],
      correctChoiceIds: ['shape-engine'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q7',
      label: 'On peut changer de moteur concret sans reecrire l abstraction principale.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Oui : c est justement l interet du decouplage Bridge.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q8',
      label: 'Quand Bridge devient-il pertinent ?',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Quand deux dimensions evoluent separement, par exemple plusieurs formes et plusieurs moteurs.',
      choices: [
        { id: 'two-dimensions', label: 'Quand forme et implementation evoluent separement' },
        { id: 'single-instance', label: 'Quand on veut une seule instance globale' },
        { id: 'simple-list', label: 'Quand on parcourt une liste' },
      ],
      correctChoiceIds: ['two-dimensions'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q9',
      label: 'Sans Bridge, on tombe souvent sur :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Les combinaisons deviennent des sous-classes concretes rigides.',
      choices: [
        { id: 'combo', label: 'Des classes du type CircleGlowShape ou TrianglePixelShape' },
        { id: 'cache', label: 'Un cache partage' },
        { id: 'pubsub', label: 'Une diffusion d evenements' },
      ],
      correctChoiceIds: ['combo'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'bridge-q10',
      label: 'Remets le flux Bridge dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client appelle l abstraction, l abstraction delegue, puis l implementation execute le rendu concret.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'client', label: 'Le client demande un rendu' },
        { id: 'abstraction', label: 'L abstraction prepare l operation' },
        { id: 'delegate', label: 'L abstraction delegue vers l implementation' },
        { id: 'implementation', label: 'Le moteur concret dessine' },
      ],
      correctOrder: ['client', 'abstraction', 'delegate', 'implementation'],
    },
  ],
}
