export const patternCode = 'composite'

export const patternDefinition = {
  code: 'composite',
  name: 'Composite',
  type: 'STRUCTURAL',
  description: 'Compose des objets en arbre pour traiter uniformement un element simple et un groupe d elements.',
  useCase: 'Construire un explorateur de dossiers et fichiers ou une action appliquee au root descend naturellement sur toute la structure.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_COMPOSITE', 'WITHOUT_COMPOSITE'],
      defaultValue: 'WITH_COMPOSITE',
    },
    {
      name: 'rootName',
      label: 'Nom du root',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'workspace',
    },
    {
      name: 'blueprintCode',
      label: 'Blueprint',
      type: 'SELECT',
      required: true,
      allowedValues: ['GAME_ASSETS', 'DESIGN_SYSTEM', 'DOCS_SPACE'],
      defaultValue: 'GAME_ASSETS',
    },
    {
      name: 'extraLeafCount',
      label: 'Feuilles supplementaires',
      type: 'NUMBER',
      required: true,
      allowedValues: null,
      defaultValue: '3',
    },
    {
      name: 'operationLabel',
      label: 'Operation',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Scan tree',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Le client parle au root, a un dossier ou a un fichier avec le meme contrat, puis la structure arborescente fait le reste.',
  intuition:
    "Composite sert a modeliser une relation part-whole. Une feuille et un groupe d elements implementent la meme abstraction, ce qui rend le parcours d arbre bien plus lisible.",
  readingGuide:
    "Observe d abord le root et la profondeur de l arbre. Ensuite compare combien de noeuds sont traites avec et sans Composite pour voir l effet sur les descendants.",
  studentAngle:
    "Le vrai declic est de voir qu un dossier et un fichier peuvent recevoir la meme operation sans que le client change de logique.",
  developerAngle:
    "Composite devient utile pour toute structure recursive: systeme de fichiers, arborescence UI, scene graph, menus ou catalogue hierarchique.",
  playfulPrompt:
    "Monte le nombre de feuilles supplementaires puis relance la demo. Tu verras tout de suite si le parcours couvre encore l arbre complet.",
  steps: [
    'Le client declenche une operation sur le root.',
    'Le root composite la relaie a ses enfants via le meme contrat.',
    'Les sous-dossiers et les feuilles executent chacun leur partie.',
    'Le resultat remonte et agrege tout le sous-arbre.',
  ],
  glossary: [
    {
      term: 'Leaf',
      definition: 'Element terminal de l arbre qui n a pas d enfants.',
    },
    {
      term: 'Part-whole',
      definition: 'Relation entre un tout et ses parties, typique des structures arborescentes.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1240 720',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 252,
      width: 244,
      height: 130,
      title: 'TreeBuilderClient',
      stereotype: 'Client',
      methods: ['+ scan(root)', '+ renderTree()'],
      tone: 'teal',
    },
    {
      id: 'component',
      x: 404,
      y: 88,
      width: 284,
      height: 132,
      title: 'WorkspaceComponent',
      stereotype: 'Component',
      methods: ['+ scan()', '+ size()', '+ label()'],
      tone: 'sand',
    },
    {
      id: 'composite',
      x: 404,
      y: 304,
      width: 308,
      height: 172,
      title: 'WorkspaceFolder',
      stereotype: 'Composite',
      fields: ['- children: List<WorkspaceComponent>'],
      methods: ['+ add(child)', '+ remove(child)', '+ scan()'],
      tone: 'accent',
    },
    {
      id: 'leaf',
      x: 826,
      y: 152,
      width: 270,
      height: 144,
      title: 'WorkspaceFile',
      stereotype: 'Leaf',
      fields: ['- sizeMb: int'],
      methods: ['+ scan()', '+ size()'],
      tone: 'teal',
    },
    {
      id: 'tree',
      x: 826,
      y: 390,
      width: 270,
      height: 126,
      title: 'TreeSnapshot',
      stereotype: 'Runtime view',
      fields: ['+ processedNodes: int', '+ totalSizeMb: int'],
      tone: 'sand',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'component',
      label: 'uses',
      marker: 'arrow',
    },
    {
      from: 'composite',
      to: 'component',
      label: 'implements',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'leaf',
      to: 'component',
      label: 'implements',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'composite',
      to: 'component',
      label: 'contains',
      marker: 'diamond',
      points: [
        { x: 742, y: 390 },
        { x: 780, y: 260 },
      ],
    },
    {
      from: 'composite',
      to: 'tree',
      label: 'builds snapshot',
      marker: 'arrow',
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'composite',
  title: 'Quiz Composite',
  description: 'Teste ta comprehension des structures arborescentes et du traitement uniforme entre groupe et feuille.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'composite-q1',
      label: 'Le pattern Composite permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Composite traite uniformement un objet simple et un groupe d objets.',
      choices: [
        { id: 'tree', label: 'Representer une arborescence part-whole' },
        { id: 'clone', label: 'Cloner un objet' },
        { id: 'notify', label: 'Notifier des abonnes' },
      ],
      correctChoiceIds: ['tree'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q2',
      label: 'Une feuille et un composite peuvent exposer le meme contrat public.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : c est le coeur du pattern, pour que le client traite les deux de facon uniforme.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q3',
      label: 'Composite appartient a la famille :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Composite est un pattern structurel.',
      choices: [
        { id: 'creational', label: 'Creation' },
        { id: 'structural', label: 'Structurel' },
        { id: 'behavioral', label: 'Comportemental' },
      ],
      correctChoiceIds: ['structural'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q4',
      label: 'Un composite represente en general :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le composite agrege des enfants et peut deleguer la meme operation a tous ses descendants.',
      choices: [
        { id: 'group', label: 'Un groupe qui contient d autres composants' },
        { id: 'leaf', label: 'Un element terminal sans enfants' },
        { id: 'db', label: 'La base de donnees' },
      ],
      correctChoiceIds: ['group'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q5',
      label: 'Associe chaque role Composite a sa responsabilite.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Component definit le contrat, Composite contient des enfants, Leaf termine la branche.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'component', label: 'Component' },
        { id: 'composite', label: 'Composite' },
        { id: 'leaf', label: 'Leaf' },
      ],
      rightItems: [
        { id: 'contract', label: 'Contrat commun' },
        { id: 'children', label: 'Contient des enfants' },
        { id: 'terminal', label: 'N a pas d enfants' },
      ],
      correctPairs: [
        { leftId: 'component', rightId: 'contract' },
        { leftId: 'composite', rightId: 'children' },
        { leftId: 'leaf', rightId: 'terminal' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q6',
      label: 'Quel exemple illustre bien Composite ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Un arbre de dossiers et fichiers est un exemple canonique du pattern Composite.',
      choices: [
        { id: 'filesystem', label: 'Un systeme de dossiers et fichiers' },
        { id: 'payment', label: 'Un mode de paiement' },
        { id: 'logger', label: 'Un logger global' },
      ],
      correctChoiceIds: ['filesystem'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q7',
      label: 'Une feuille possede en general d autres enfants.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Non : une leaf marque le bout d une branche et ne contient pas d enfants.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['false'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q8',
      label: 'Composite aide surtout a :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le pattern simplifie les parcours et les operations recursives sur tout un arbre.',
      choices: [
        { id: 'recursion', label: 'Appliquer une operation recursive sur tout un arbre' },
        { id: 'memory', label: 'Partager la memoire' },
        { id: 'events', label: 'Diffuser des notifications' },
      ],
      correctChoiceIds: ['recursion'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q9',
      label: 'Le client depend idealement de :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client parle a l abstraction Component et ignore s il manipule une feuille ou un composite.',
      choices: [
        { id: 'component', label: 'L abstraction Component' },
        { id: 'leaf', label: 'La classe Leaf concrete' },
        { id: 'folder', label: 'La classe Composite concrete' },
      ],
      correctChoiceIds: ['component'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'composite-q10',
      label: 'Remets la boucle Composite dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client appelle le component, le composite relaie aux enfants, les feuilles executent, puis le resultat remonte.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'call', label: 'Le client appelle le contrat Component' },
        { id: 'delegate', label: 'Le Composite relaie l operation aux enfants' },
        { id: 'leaf', label: 'Les feuilles executent leur partie' },
        { id: 'return', label: 'Le resultat remonte dans l arbre' },
      ],
      correctOrder: ['call', 'delegate', 'leaf', 'return'],
    },
  ],
}
