export const patternCode = 'prototype'

export const patternDefinition = {
  code: 'prototype',
  name: 'Prototype',
  type: 'CREATIONAL',
  description: 'Duplique un objet deja configure pour creer rapidement de nouvelles variantes sans repasser par toute la construction.',
  useCase: 'Cloner un robot, un drone ou un avatar puis observer la difference entre copie superficielle et copie profonde.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_PROTOTYPE', 'WITHOUT_PROTOTYPE'],
      defaultValue: 'WITH_PROTOTYPE',
    },
    {
      name: 'blueprintName',
      label: 'Nom du blueprint',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Echo Forge',
    },
    {
      name: 'archetype',
      label: 'Archetype source',
      type: 'SELECT',
      required: true,
      allowedValues: ['SCOUT_DRONE', 'SIEGE_MECH', 'ARCANE_SENTINEL'],
      defaultValue: 'SCOUT_DRONE',
    },
    {
      name: 'cloneCount',
      label: 'Nombre de clones',
      type: 'NUMBER',
      required: true,
      allowedValues: null,
      defaultValue: '4',
    },
    {
      name: 'mutationTarget',
      label: 'Clone a muter',
      type: 'SELECT',
      required: true,
      allowedValues: ['CLONE_2', 'CLONE_3', 'CLONE_4', 'CLONE_5', 'CLONE_6'],
      defaultValue: 'CLONE_2',
    },
    {
      name: 'mutationPreset',
      label: 'Mutation appliquee',
      type: 'SELECT',
      required: true,
      allowedValues: ['OVERCLOCK', 'FORTIFY', 'STEALTH'],
      defaultValue: 'OVERCLOCK',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Un objet modele sert de gabarit, puis ses clones vivent ou non leur propre vie interne.',
  intuition:
    "Prototype evite de reconstruire un objet complexe depuis zero. Le vrai point pedagogique est de voir ce qui est duplique en profondeur et ce qui reste partage par erreur.",
  readingGuide:
    "Observe d abord le prototype source, puis les clones avant mutation. Quand la mutation arrive, compare combien de cartes changent selon le mode choisi.",
  studentAngle:
    "Le declic est simple : une copie superficielle peut sembler correcte tant qu on ne touche pas a l etat imbrique. Des qu on le modifie, la fuite devient visible.",
  developerAngle:
    "Prototype est pertinent quand un objet est couteux a preparer, qu il existe deja bien configure, et qu on veut multiplier les variantes sans repasser par toute la construction.",
  playfulPrompt:
    "Change l archetype, augmente le nombre de clones puis applique une mutation. Regarde si un seul clone change ou si tout l essaim se synchronise.",
  steps: [
    'Un prototype source est configure une fois.',
    'Les clones sont dupliques a partir de ce modele.',
    'Un clone cible recoit une mutation sur son etat imbrique.',
    'Le systeme revele si la mutation reste locale ou fuit vers les autres clones.',
  ],
  glossary: [
    {
      term: 'Copie superficielle',
      definition: 'Copie les champs visibles mais peut conserver les memes references imbriquees.',
    },
    {
      term: 'Copie profonde',
      definition: 'Duplique aussi les objets imbriques pour isoler l etat de chaque clone.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1180 720',
  classes: [
    {
      id: 'client',
      x: 72,
      y: 250,
      width: 248,
      height: 132,
      title: 'CloneFactoryClient',
      stereotype: 'Client',
      methods: ['+ choosePrototype()', '+ requestClone()'],
      tone: 'teal',
    },
    {
      id: 'prototype',
      x: 404,
      y: 60,
      width: 282,
      height: 126,
      title: 'CombatPrototype',
      stereotype: 'Prototype',
      methods: ['+ clone()', '+ deepClone()'],
      tone: 'sand',
    },
    {
      id: 'concrete',
      x: 404,
      y: 290,
      width: 300,
      height: 176,
      title: 'CombatUnitPrototype',
      stereotype: 'Concrete Prototype',
      fields: ['- shell: String', '- module: CompanionState'],
      methods: ['+ clone()', '+ mutateModule()'],
      tone: 'accent',
    },
    {
      id: 'module',
      x: 824,
      y: 86,
      width: 250,
      height: 140,
      title: 'CompanionState',
      stereotype: 'Nested State',
      fields: ['+ effect: String', '+ syncKey: String'],
      tone: 'teal',
    },
    {
      id: 'clone',
      x: 824,
      y: 332,
      width: 260,
      height: 144,
      title: 'ClonedUnit',
      stereotype: 'Clone',
      fields: ['+ attack: int', '+ defense: int', '+ speed: int'],
      tone: 'accent',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'prototype',
      label: 'requests clone',
      marker: 'arrow',
    },
    {
      from: 'concrete',
      to: 'prototype',
      fromSide: 'top',
      toSide: 'bottom',
      label: 'implements',
      labelX: 552,
      labelY: 246,
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'concrete',
      to: 'module',
      label: 'owns or shares',
      marker: 'diamond',
    },
    {
      from: 'concrete',
      to: 'clone',
      label: 'clone()',
      marker: 'arrow',
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'prototype',
  title: 'Quiz Prototype',
  description: 'Valide ta comprehension du clonage, de la copie superficielle et de la copie profonde.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'prototype-q1',
      label: 'Le pattern Prototype permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Prototype sert a dupliquer rapidement un objet deja configure.',
      choices: [
        { id: 'clone', label: 'Cloner un objet existant' },
        { id: 'notify', label: 'Notifier des abonnes' },
        { id: 'share', label: 'Partager la memoire d affichage' },
      ],
      correctChoiceIds: ['clone'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q2',
      label: 'Prototype appartient a la famille des patterns de creation.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : il cree de nouveaux objets a partir d une instance source deja configuree.',
      choices: [
        { id: 'true', label: 'Vrai' },
        { id: 'false', label: 'Faux' },
      ],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q3',
      label: 'Dans une copie superficielle, le risque principal concerne :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Une copie superficielle peut conserver les memes references imbriquees entre plusieurs clones.',
      choices: [
        { id: 'nested', label: 'Les references imbriquees partagees' },
        { id: 'syntax', label: 'La syntaxe du constructeur' },
        { id: 'network', label: 'Le reseau' },
      ],
      correctChoiceIds: ['nested'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q4',
      label: 'Une copie profonde signifie que :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Les objets imbriques sont aussi dupliques, donc chaque clone porte son propre etat.',
      choices: [
        { id: 'same', label: 'Tous les clones gardent la meme reference imbriquee' },
        { id: 'deep', label: 'Les objets imbriques sont dupliques eux aussi' },
        { id: 'none', label: 'Aucun clone n est cree' },
      ],
      correctChoiceIds: ['deep'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q5',
      label: 'Associe chaque notion Prototype a son effet.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le prototype source sert de modele, la shallow copy partage des references, la deep copy les isole.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'source', label: 'Prototype source' },
        { id: 'shallow', label: 'Copie superficielle' },
        { id: 'deep', label: 'Copie profonde' },
      ],
      rightItems: [
        { id: 'model', label: 'Objet modele deja configure' },
        { id: 'shared', label: 'References imbriquees partagees' },
        { id: 'isolated', label: 'Etat imbrique isole' },
      ],
      correctPairs: [
        { leftId: 'source', rightId: 'model' },
        { leftId: 'shallow', rightId: 'shared' },
        { leftId: 'deep', rightId: 'isolated' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q6',
      label: 'Quel cas colle bien a Prototype ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Cloner rapidement des ennemis, des drones ou des cartes deja configurees est un bon usage de Prototype.',
      choices: [
        { id: 'clones', label: 'Cloner des drones deja equipes' },
        { id: 'events', label: 'Diffuser des notifications' },
        { id: 'commands', label: 'Historiser undo / redo' },
      ],
      correctChoiceIds: ['clones'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q7',
      label: 'Modifier un objet imbrique partage peut impacter plusieurs clones.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'C est exactement le piege montre par la copie superficielle.',
      choices: [
        { id: 'true', label: 'Vrai' },
        { id: 'false', label: 'Faux' },
      ],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q8',
      label: 'Le principal interet de Prototype est de :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'On evite de reconfigurer l objet depuis zero a chaque creation.',
      choices: [
        { id: 'repeat', label: 'Repartir de zero a chaque fois' },
        { id: 'reuse', label: 'Reutiliser un objet modele deja configure' },
        { id: 'switch', label: 'Remplacer des switch' },
      ],
      correctChoiceIds: ['reuse'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q9',
      label: 'Sans copie profonde, une mutation locale peut :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Si les references restent partagees, une mutation locale fuit vers les autres clones.',
      choices: [
        { id: 'leak', label: 'Se propager a d autres clones' },
        { id: 'compile', label: 'Casser la compilation' },
        { id: 'none', label: 'Rester toujours isolee' },
      ],
      correctChoiceIds: ['leak'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'prototype-q10',
      label: 'Remets le flux Prototype dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'On prepare un modele, on clone, on ajuste un clone, puis on observe si l etat reste isole ou non.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'seed', label: 'Configurer le prototype source' },
        { id: 'clone', label: 'Dupliquer plusieurs clones' },
        { id: 'mutate', label: 'Modifier un clone cible' },
        { id: 'observe', label: 'Observer isolation ou propagation' },
      ],
      correctOrder: ['seed', 'clone', 'mutate', 'observe'],
    },
  ],
}
