export const patternCode = 'interpreter'

export const patternDefinition = {
  code: 'interpreter',
  name: 'Interpreter',
  type: 'BEHAVIORAL',
  description: 'Interprete un mini langage en transformant chaque instruction en expression executable sur un contexte.',
  useCase: 'Ecrire un petit script MOVE / TURN / ATTACK / REPEAT puis voir si le personnage atteint la cible selon qu un interprete complet existe ou non.',
  complexityLevel: 'ADVANCED',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_INTERPRETER', 'WITHOUT_INTERPRETER'],
      defaultValue: 'WITH_INTERPRETER',
    },
    {
      name: 'missionName',
      label: 'Nom de la mission',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Target Dummy Drill',
    },
    {
      name: 'objective',
      label: 'Objectif',
      type: 'SELECT',
      required: true,
      allowedValues: ['TARGET_DUMMY', 'RELAY_BEACON', 'GATE_SWITCH'],
      defaultValue: 'TARGET_DUMMY',
    },
    {
      name: 'scriptLines',
      label: 'Script',
      type: 'LIST',
      required: true,
      allowedValues: null,
      defaultValue: 'MOVE 1\nTURN RIGHT\nMOVE 1\nTURN LEFT\nREPEAT 2 {\nMOVE 1\n}\nATTACK',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Le code tape par l utilisateur devient un vrai langage interprete et non une simple suite de chaines scannees a la main.',
  intuition:
    "Interpreter est utile quand un domaine commence a ressembler a un mini langage. Chaque symbole devient une expression capable d agir sur un contexte commun.",
  readingGuide:
    "Observe d abord le script et la ligne surlignee, puis compare le parcours de la mission. En mode sans pattern, le bloc REPEAT n est plus compris comme une structure du langage.",
  studentAngle:
    "Le declic pedagogique, c est de voir qu un langage simple peut etre modelise proprement avec un arbre d expressions au lieu d un gros if / else fragile.",
  developerAngle:
    "Interpreter reste interessant pour des DSL modestes, des filtres ou des scripts encadres. Au dela, il faut souvent un parseur plus robuste ou un vrai moteur dedie.",
  playfulPrompt:
    "Modifie le script, change l objectif puis observe si le personnage atteint la cible. Ajoute ou retire le bloc REPEAT pour voir la difference en direct.",
  steps: [
    'Le joueur ecrit une suite d instructions dans un mini langage.',
    'Le parseur transforme les lignes en expressions et en blocs imbriques.',
    'Chaque expression interprete le meme contexte de mission.',
    'Le systeme montre si le script atteint vraiment la cible et quelles lignes ont ete executees.',
  ],
  glossary: [
    {
      term: 'Expression',
      definition: 'Element du langage capable de s interpreter lui-meme sur un contexte.',
    },
    {
      term: 'Contexte',
      definition: 'Etat courant partage par les expressions pendant l execution.',
    },
    {
      term: 'AST',
      definition: 'Arbre syntaxique abstrait qui represente la structure du script interprete.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1220 760',
  classes: [
    {
      id: 'client',
      x: 56,
      y: 276,
      width: 248,
      height: 132,
      title: 'ScriptAuthor',
      stereotype: 'Client',
      methods: ['+ writeScript()', '+ runMission()'],
      tone: 'teal',
    },
    {
      id: 'expression',
      x: 380,
      y: 54,
      width: 288,
      height: 132,
      title: 'ScriptExpression',
      stereotype: 'Expression',
      methods: ['+ interpret(context)', '+ flattenTree()'],
      tone: 'sand',
    },
    {
      id: 'primitive',
      x: 374,
      y: 274,
      width: 308,
      height: 164,
      title: 'PrimitiveExpression',
      stereotype: 'Terminal Expression',
      fields: ['- type: PrimitiveInstructionType', '- amount: int'],
      methods: ['+ interpret(context)'],
      tone: 'accent',
    },
    {
      id: 'repeat',
      x: 374,
      y: 516,
      width: 308,
      height: 164,
      title: 'RepeatExpression',
      stereotype: 'Non Terminal Expression',
      fields: ['- repeatCount: int', '- children: List<Expression>'],
      methods: ['+ interpret(context)'],
      tone: 'teal',
    },
    {
      id: 'context',
      x: 818,
      y: 120,
      width: 280,
      height: 152,
      title: 'InterpreterContext',
      stereotype: 'Context',
      fields: ['+ x: int', '+ y: int', '+ facing: Facing'],
      methods: ['+ moveOne()', '+ turnLeft()', '+ attack()'],
      tone: 'sand',
    },
    {
      id: 'parser',
      x: 806,
      y: 406,
      width: 302,
      height: 150,
      title: 'ScriptParser',
      stereotype: 'Parser',
      methods: ['+ parse(lines)', '+ parseBlock()'],
      tone: 'accent',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'parser',
      label: 'writes script',
      marker: 'arrow',
    },
    {
      from: 'parser',
      to: 'expression',
      label: 'builds',
      marker: 'arrow',
    },
    {
      from: 'primitive',
      to: 'expression',
      fromSide: 'top',
      toSide: 'bottom',
      label: 'implements',
      marker: 'triangle',
      dashed: true,
      labelX: 528,
      labelY: 250,
    },
    {
      from: 'repeat',
      to: 'expression',
      fromSide: 'top',
      toSide: 'bottom',
      label: 'implements',
      marker: 'triangle',
      dashed: true,
      labelX: 536,
      labelY: 492,
    },
    {
      from: 'repeat',
      to: 'primitive',
      label: 'contains',
      marker: 'diamond',
    },
    {
      from: 'expression',
      to: 'context',
      label: 'interpret(context)',
      marker: 'arrow',
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'interpreter',
  title: 'Quiz Interpreter',
  description: 'Teste ta comprehension du parsing, des expressions et de l execution d un mini langage.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'interpreter-q1',
      label: 'Le pattern Interpreter sert surtout a :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Interpreter execute un langage ou une grammaire a partir d expressions.',
      choices: [
        { id: 'language', label: 'Executer un mini langage' },
        { id: 'notify', label: 'Notifier des abonnes' },
        { id: 'share', label: 'Partager la memoire' },
      ],
      correctChoiceIds: ['language'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q2',
      label: 'Interpreter appartient a la famille des patterns comportementaux.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : il decrit comment interpreter des commandes a partir d un contexte.',
      choices: [
        { id: 'true', label: 'Vrai' },
        { id: 'false', label: 'Faux' },
      ],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q3',
      label: 'Dans une solution Interpreter, chaque symbole du langage devient souvent :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Chaque instruction ou regle est representee par une expression capable de s interpreter elle-meme.',
      choices: [
        { id: 'class', label: 'Une expression ou une classe' },
        { id: 'cookie', label: 'Un cookie' },
        { id: 'style', label: 'Une feuille CSS' },
      ],
      correctChoiceIds: ['class'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q4',
      label: 'Le contexte dans Interpreter contient en general :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le contexte stocke l etat courant utile a l execution des expressions.',
      choices: [
        { id: 'state', label: 'L etat courant de l execution' },
        { id: 'images', label: 'Uniquement des images' },
        { id: 'none', label: 'Aucune donnee' },
      ],
      correctChoiceIds: ['state'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q5',
      label: 'Associe chaque notion Interpreter a son role.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le contexte porte l etat, l expression execute une regle et la grammaire structure le langage.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'context', label: 'Context' },
        { id: 'expression', label: 'Expression' },
        { id: 'grammar', label: 'Grammar' },
      ],
      rightItems: [
        { id: 'state', label: 'Etat de l execution' },
        { id: 'rule', label: 'Regle executable' },
        { id: 'language', label: 'Structure du langage' },
      ],
      correctPairs: [
        { leftId: 'context', rightId: 'state' },
        { leftId: 'expression', rightId: 'rule' },
        { leftId: 'grammar', rightId: 'language' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q6',
      label: 'Quel cas colle bien a Interpreter ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Un mini langage de commandes, de filtres ou de regles correspond bien au pattern.',
      choices: [
        { id: 'script', label: 'Un script MOVE / TURN / ATTACK' },
        { id: 'socket', label: 'Un driver reseau bas niveau' },
        { id: 'image', label: 'Une simple image statique' },
      ],
      correctChoiceIds: ['script'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q7',
      label: 'Un bloc REPEAT peut etre represente par une expression composite contenant d autres expressions.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'C est une bonne facon de modeliser un petit langage imbrique.',
      choices: [
        { id: 'true', label: 'Vrai' },
        { id: 'false', label: 'Faux' },
      ],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q8',
      label: 'Sans Interpreter, un client qui lit le script a la main risque surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Les structures plus riches comme les blocs ou les conditions deviennent fragiles sans modele formel du langage.',
      choices: [
        { id: 'fragile', label: 'Multiplier les if / else fragiles' },
        { id: 'memory', label: 'Optimiser la memoire automatiquement' },
        { id: 'share', label: 'Partager les textures' },
      ],
      correctChoiceIds: ['fragile'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q9',
      label: 'Le vrai gain pedagogique du pattern Interpreter est de montrer :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'On voit la difference entre lire des chaines a la main et modeliser une vraie grammaire executable.',
      choices: [
        { id: 'parse', label: 'Parsing + arbre syntaxique + execution' },
        { id: 'db', label: 'Tables SQL + migrations' },
        { id: 'cache', label: 'Cache HTTP' },
      ],
      correctChoiceIds: ['parse'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'interpreter-q10',
      label: 'Remets le flux Interpreter dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'On ecrit le script, on le parse, on construit les expressions, puis on execute le contexte.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'write', label: 'Ecrire le script' },
        { id: 'parse', label: 'Parser les lignes' },
        { id: 'ast', label: 'Construire les expressions' },
        { id: 'run', label: 'Executer le contexte' },
      ],
      correctOrder: ['write', 'parse', 'ast', 'run'],
    },
  ],
}
