export const patternCode = 'iterator'

export const patternDefinition = {
  code: 'iterator',
  name: 'Iterator',
  type: 'BEHAVIORAL',
  description: 'Expose un parcours sequentiel sur une collection sans reveler sa structure interne ni dupliquer la logique de navigation.',
  useCase: 'Parcourir une liste ou un arbre avec un curseur next / previous stable, meme quand la structure sous-jacente change.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_ITERATOR', 'WITHOUT_ITERATOR'],
      defaultValue: 'WITH_ITERATOR',
    },
    {
      name: 'collectionCode',
      label: 'Collection',
      type: 'SELECT',
      required: true,
      allowedValues: ['QUEST_LOG', 'ASSET_TREE', 'TOOLBELT'],
      defaultValue: 'ASSET_TREE',
    },
    {
      name: 'explorerName',
      label: 'Nom de l explorateur',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Traversal Explorer',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Le client avance avec next() et previous() sans connaitre le stockage reel de la collection.',
  intuition:
    "Iterator sert a cacher la facon dont on parcourt une collection. Le client ne manipule plus des index, des bornes ou des branches sur un arbre : il demande simplement l element suivant ou precedent.",
  readingGuide:
    "Observe d abord la collection et le curseur courant. Ensuite suis la timeline next / previous pour voir comment le mode sans Iterator laisse fuir la logique de navigation dans le client.",
  studentAngle:
    "Le declic pedagogique est que le pattern ne change pas les elements eux-memes. Il encapsule uniquement la navigation entre eux.",
  developerAngle:
    "Iterator devient utile pour encapsuler un parcours sur liste, arbre, graphe aplati ou resultat pagine, surtout quand tu veux garder un contrat stable pour le client.",
  playfulPrompt:
    "Teste Quest Log, Asset Tree et Toolbelt. Observe surtout le retour arriere : avec Iterator il reste stable, sans Iterator il devient plus manuel et plus fragile.",
  steps: [
    'Le client demande un iterator sur la collection.',
    'Le curseur se place sur un premier element.',
    'Les appels next() et previous() font avancer ou reculer le parcours.',
    'Le client lit les elements sans connaitre la structure interne.',
  ],
  glossary: [
    {
      term: 'Curseur',
      definition: 'Position courante de l iterator sur la collection.',
    },
    {
      term: 'Parcours bidirectionnel',
      definition: 'Navigation qui permet d aller au suivant et de revenir au precedent.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1220 720',
  classes: [
    {
      id: 'client',
      x: 76,
      y: 260,
      width: 244,
      height: 128,
      title: 'TraversalClient',
      stereotype: 'Client',
      methods: ['+ browse()', '+ renderCurrent()'],
      tone: 'teal',
    },
    {
      id: 'iterator',
      x: 396,
      y: 104,
      width: 286,
      height: 168,
      title: 'CollectionIterator',
      stereotype: 'Iterator',
      methods: ['+ next()', '+ previous()', '+ hasNext()', '+ current()'],
      tone: 'accent',
    },
    {
      id: 'concrete',
      x: 396,
      y: 360,
      width: 286,
      height: 146,
      title: 'DepthFirstIterator',
      stereotype: 'Concrete Iterator',
      fields: ['- cursor: int'],
      methods: ['+ next()', '+ previous()'],
      tone: 'sand',
    },
    {
      id: 'aggregate',
      x: 784,
      y: 126,
      width: 286,
      height: 150,
      title: 'TraversableCollection',
      stereotype: 'Aggregate',
      methods: ['+ createIterator()', '+ size()'],
      tone: 'teal',
    },
    {
      id: 'items',
      x: 784,
      y: 378,
      width: 286,
      height: 128,
      title: 'CollectionItem',
      stereotype: 'Element',
      methods: ['+ label()', '+ depth()'],
      tone: 'sand',
    },
  ],
  relations: [
    { from: 'client', to: 'aggregate', label: 'asks iterator', marker: 'arrow' },
    { from: 'aggregate', to: 'iterator', label: 'creates', marker: 'arrow' },
    { from: 'concrete', to: 'iterator', label: 'implements', marker: 'triangle', dashed: true },
    { from: 'aggregate', to: 'items', label: 'contains', marker: 'diamond' },
    { from: 'iterator', to: 'items', label: 'traverses', marker: 'arrow' },
  ],
}

export const fallbackQuiz = {
  patternCode: 'iterator',
  title: 'Quiz Iterator',
  description: 'Teste ta comprehension du parcours sequentiel cache derriere next() et previous().',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'iterator-q1',
      label: 'Le pattern Iterator permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Iterator fournit un parcours uniforme sans exposer la structure interne.',
      choices: [
        { id: 'traverse', label: 'Parcourir une collection sans exposer sa structure' },
        { id: 'decorate', label: 'Empiler des comportements' },
        { id: 'clone', label: 'Cloner un objet' },
      ],
      correctChoiceIds: ['traverse'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q2',
      label: 'Iterator appartient aux patterns comportementaux.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : il traite la maniere de parcourir les elements.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q3',
      label: 'Le client devrait idealement connaitre :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client manipule next() / hasNext() plutot que la representation concrete de la collection.',
      choices: [
        { id: 'cursor', label: 'Le contrat de parcours' },
        { id: 'storage', label: 'Le tableau ou l arbre concret en detail' },
        { id: 'sql', label: 'La requete SQL brute' },
      ],
      correctChoiceIds: ['cursor'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q4',
      label: 'Quel benefice est typique d Iterator ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Le parcours reste stable meme si la collection change de structure interne.',
      choices: [
        { id: 'decouple', label: 'Decoupler le parcours de la structure' },
        { id: 'single', label: 'Garantir une instance unique' },
        { id: 'share', label: 'Partager la memoire' },
      ],
      correctChoiceIds: ['decouple'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q5',
      label: 'Associe chaque role Iterator a sa responsabilite.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le client demande, l iterator avance et la collection fournit les elements.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'client', label: 'Client' },
        { id: 'iterator', label: 'Iterator' },
        { id: 'collection', label: 'Collection' },
      ],
      rightItems: [
        { id: 'ask', label: 'Demande next / previous' },
        { id: 'move', label: 'Deplace le curseur' },
        { id: 'store', label: 'Contient les elements' },
      ],
      correctPairs: [
        { leftId: 'client', rightId: 'ask' },
        { leftId: 'iterator', rightId: 'move' },
        { leftId: 'collection', rightId: 'store' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q6',
      label: 'Un iterator bidirectionnel ajoute surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Il ajoute previous() en plus du parcours avant.',
      choices: [
        { id: 'previous', label: 'La navigation previous()' },
        { id: 'clone', label: 'Le clonage profond' },
        { id: 'notify', label: 'Les notifications d evenement' },
      ],
      correctChoiceIds: ['previous'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q7',
      label: 'Sans Iterator, la logique de navigation a tendance a fuir dans le client.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Oui : index, bornes et retour arriere finissent dans le code appelant.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q8',
      label: 'Quel cas illustre bien Iterator ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Un explorateur next / previous sur une liste ou un arbre aplati illustre tres bien Iterator.',
      choices: [
        { id: 'explorer', label: 'Un Traversal Explorer avec curseur' },
        { id: 'powerup', label: 'Des power-ups empiles' },
        { id: 'facade', label: 'Un bouton Start unique' },
      ],
      correctChoiceIds: ['explorer'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q9',
      label: 'Iterator masque principalement :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Il masque la representation et le mecanisme concret de parcours.',
      choices: [
        { id: 'representation', label: 'La representation et le mecanisme de parcours' },
        { id: 'database', label: 'La base de donnees complete' },
        { id: 'ui', label: 'Le style CSS' },
      ],
      correctChoiceIds: ['representation'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'iterator-q10',
      label: 'Remets le parcours Iterator dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'On verifie hasNext, on lit next, on deplace le curseur puis on traite l element courant.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'check', label: 'Verifier si un element est disponible' },
        { id: 'next', label: 'Appeler next()' },
        { id: 'move', label: 'Deplacer le curseur' },
        { id: 'use', label: 'Utiliser l element courant' },
      ],
      correctOrder: ['check', 'next', 'move', 'use'],
    },
  ],
}
