export const patternCode = 'visitor'

export const patternDefinition = {
  code: 'visitor',
  name: 'Visitor',
  type: 'BEHAVIORAL',
  description: 'Ajoute des operations sur une structure existante sans modifier les classes des elements parcourus.',
  useCase: 'Analyser un arbre de dossiers et de fichiers avec plusieurs visiteurs : compter, valoriser, rechercher ou scanner.',
  complexityLevel: 'ADVANCED',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_VISITOR', 'WITHOUT_VISITOR'],
      defaultValue: 'WITH_VISITOR',
    },
    {
      name: 'treePreset',
      label: 'Structure',
      type: 'SELECT',
      required: true,
      allowedValues: ['ASSET_PACK', 'TEAM_WORKSPACE', 'MEDIA_ARCHIVE'],
      defaultValue: 'ASSET_PACK',
    },
    {
      name: 'visitorType',
      label: 'Visitor',
      type: 'SELECT',
      required: true,
      allowedValues: ['COUNT_ELEMENTS', 'CALCULATE_VALUE', 'FIND_ELEMENT', 'VIRUS_SCAN'],
      defaultValue: 'COUNT_ELEMENTS',
    },
    {
      name: 'searchTerm',
      label: 'Terme de recherche',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'virus',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'La structure reste stable pendant que les analyses changent en remplaçant simplement le visitor.',
  intuition:
    "Visitor est tres fort quand tu as une structure riche, comme un arbre de dossiers, et que tu veux lui ajouter plusieurs traitements sans rouvrir les classes de base a chaque fois.",
  readingGuide:
    "Regarde d abord l arbre, puis suis la ligne active du parcours. Change ensuite de visitor pour voir que le trajet reste similaire mais que le resultat final change completement.",
  studentAngle:
    "Le declic est de distinguer la structure des donnees et l operation appliquee dessus. Les dossiers et fichiers ne changent pas, c est le visitor qui change.",
  developerAngle:
    "Visitor est adapte a une hierarchie stable sur laquelle on ajoute souvent de nouveaux calculs, rapports ou scanners. Le compromis arrive surtout quand on ajoute de nouveaux types d elements.",
  playfulPrompt:
    "Teste Count, Value, Find et Virus Scan sur les trois presets. Observe comment le chemin reste lisible pendant que la mission du visitor change.",
  steps: [
    'Le client choisit un visitor specialise.',
    'Le root de la structure lance accept(visitor).',
    'Chaque element dispatch automatiquement vers la bonne visite.',
    'Le visitor agrege son resultat sans modifier les classes des noeuds.',
  ],
  glossary: [
    {
      term: 'Double dispatch',
      definition: 'Mecanisme qui permet d appeler la bonne visite selon le type concret de l element rencontre.',
    },
    {
      term: 'Structure stable',
      definition: 'Hierarchie d elements qui change peu, tandis que les operations appliquees evoluent souvent.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1260 780',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 280,
      width: 248,
      height: 132,
      title: 'StructureAnalyzerClient',
      stereotype: 'Client',
      methods: ['+ chooseVisitor()', '+ runAnalysis()'],
      tone: 'teal',
    },
    {
      id: 'visitor',
      x: 382,
      y: 72,
      width: 286,
      height: 156,
      title: 'StructureVisitor',
      stereotype: 'Visitor',
      methods: ['+ visitFolder(folder)', '+ visitFile(file)', '+ buildResult()'],
      tone: 'accent',
    },
    {
      id: 'concrete',
      x: 382,
      y: 316,
      width: 296,
      height: 170,
      title: 'CountElementsVisitor',
      stereotype: 'Concrete Visitor',
      fields: ['- folderCount: int', '- fileCount: int'],
      methods: ['+ visitFolder()', '+ visitFile()'],
      tone: 'sand',
    },
    {
      id: 'element',
      x: 760,
      y: 70,
      width: 288,
      height: 150,
      title: 'WorkspaceComponent',
      stereotype: 'Element',
      methods: ['+ accept(visitor)', '+ children()'],
      tone: 'teal',
    },
    {
      id: 'folder',
      x: 760,
      y: 294,
      width: 256,
      height: 150,
      title: 'WorkspaceFolder',
      stereotype: 'Concrete Element',
      methods: ['+ accept(visitor)', '+ flatten()'],
      tone: 'accent',
    },
    {
      id: 'file',
      x: 760,
      y: 518,
      width: 256,
      height: 150,
      title: 'WorkspaceFile',
      stereotype: 'Concrete Element',
      fields: ['+ sizeMb: int', '+ infected: boolean'],
      methods: ['+ accept(visitor)'],
      tone: 'sand',
    },
  ],
  relations: [
    {
      from: 'client',
      to: 'visitor',
      label: 'selects',
      marker: 'arrow',
    },
    {
      from: 'client',
      to: 'element',
      label: 'starts traversal',
      marker: 'arrow',
    },
    {
      from: 'concrete',
      to: 'visitor',
      label: 'implements',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'folder',
      to: 'element',
      label: 'extends',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'file',
      to: 'element',
      label: 'extends',
      marker: 'triangle',
      dashed: true,
    },
    {
      from: 'element',
      to: 'visitor',
      label: 'accept(visitor)',
      marker: 'arrow',
    },
  ],
}

export const fallbackQuiz = {
  patternCode: 'visitor',
  title: 'Quiz Visitor',
  description: 'Teste ta comprehension du parcours d une structure et de l ajout de nouveaux comportements via un visitor.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'visitor-q1',
      label: 'Le pattern Visitor permet surtout de :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Visitor ajoute une nouvelle operation sur une structure stable sans modifier les classes des elements.',
      choices: [
        { id: 'behavior', label: 'Ajouter un comportement sans modifier les elements' },
        { id: 'clone', label: 'Cloner des objets' },
        { id: 'memory', label: 'Partager la memoire' },
      ],
      correctChoiceIds: ['behavior'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q2',
      label: 'Visitor appartient a la famille des patterns comportementaux.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : Visitor deplace le comportement de traitement hors des elements.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q3',
      label: 'Chaque element de la structure expose en general :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Chaque element propose une methode accept(visitor) pour dispatcher sur la bonne visite.',
      choices: [
        { id: 'accept', label: 'Une methode accept(visitor)' },
        { id: 'factory', label: 'Une factory statique' },
        { id: 'singleton', label: 'Une instance globale' },
      ],
      correctChoiceIds: ['accept'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q4',
      label: 'Quel cas illustre bien Visitor ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Analyser un arbre de dossiers avec plusieurs traitements est un cas tres parlant.',
      choices: [
        { id: 'tree', label: 'Analyser un arbre de fichiers avec plusieurs vues' },
        { id: 'payment', label: 'Changer un mode de paiement' },
        { id: 'cache', label: 'Mettre en cache une ressource' },
      ],
      correctChoiceIds: ['tree'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q5',
      label: 'Associe chaque role Visitor a sa responsabilite.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Les elements acceptent, le visitor declare les operations, le concrete visitor porte l analyse.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'element', label: 'Element' },
        { id: 'visitor', label: 'Visitor' },
        { id: 'concrete', label: 'ConcreteVisitor' },
      ],
      rightItems: [
        { id: 'accept', label: 'Expose accept(visitor)' },
        { id: 'contract', label: 'Declare les visites' },
        { id: 'logic', label: 'Implemente un calcul concret' },
      ],
      correctPairs: [
        { leftId: 'element', rightId: 'accept' },
        { leftId: 'visitor', rightId: 'contract' },
        { leftId: 'concrete', rightId: 'logic' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q6',
      label: 'Ajouter un nouveau Visitor evite souvent de modifier les classes d elements existantes.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Oui : c est l interet principal quand la structure est stable mais que les analyses evoluent.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q7',
      label: 'Le principal inconvenient de Visitor apparait quand :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Ajouter un nouveau type d element force souvent a faire evoluer tous les visitors existants.',
      choices: [
        { id: 'element', label: 'On ajoute souvent de nouveaux types d elements' },
        { id: 'analysis', label: 'On ajoute de nouvelles analyses' },
        { id: 'logs', label: 'On ajoute des logs' },
      ],
      correctChoiceIds: ['element'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q8',
      label: 'Visitor fonctionne tres bien avec :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Visitor et Composite forment un duo classique pour parcourir un arbre uniforme.',
      choices: [
        { id: 'composite', label: 'Composite' },
        { id: 'singleton', label: 'Singleton' },
        { id: 'proxy', label: 'Proxy' },
      ],
      correctChoiceIds: ['composite'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q9',
      label: 'Dans le flux Visitor, le double dispatch sert a :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Il permet d appeler la bonne methode de visite selon le type concret de l element.',
      choices: [
        { id: 'dispatch', label: 'Choisir la bonne visite selon l element concret' },
        { id: 'cache', label: 'Mettre la structure en cache' },
        { id: 'clone', label: 'Dupliquer les noeuds' },
      ],
      correctChoiceIds: ['dispatch'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'visitor-q10',
      label: 'Remets le flux Visitor dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client choisit le visitor, le root accepte, chaque element dispatch sa visite, puis le resultat s agrege.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'choose', label: 'Le client choisit un visitor' },
        { id: 'accept', label: 'Le root lance accept(visitor)' },
        { id: 'visit', label: 'Chaque element appelle la bonne visite' },
        { id: 'result', label: 'Le resultat final est agrege' },
      ],
      correctOrder: ['choose', 'accept', 'visit', 'result'],
    },
  ],
}
