export const patternCode = 'memento'

export const patternDefinition = {
  code: 'memento',
  name: 'Memento',
  type: 'BEHAVIORAL',
  description: 'Capture et restaure un etat interne sans exposer directement les details de cet etat au client.',
  useCase: 'Sauvegarder une scene, appliquer des mutations risquees puis restaurer proprement un checkpoint comme dans un jeu ou un éditeur.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_MEMENTO', 'WITHOUT_MEMENTO'],
      defaultValue: 'WITH_MEMENTO',
    },
    {
      name: 'presetCode',
      label: 'Scene',
      type: 'SELECT',
      required: true,
      allowedValues: ['PIXEL_GARDEN', 'ARCADE_HUB', 'CONTROL_ROOM'],
      defaultValue: 'PIXEL_GARDEN',
    },
    {
      name: 'workspaceName',
      label: 'Nom de la session',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Save & Restore',
    },
    {
      name: 'restoreTarget',
      label: 'Checkpoint a restaurer',
      type: 'SELECT',
      required: true,
      allowedValues: ['SNAPSHOT_ALPHA', 'SNAPSHOT_BETA'],
      defaultValue: 'SNAPSHOT_ALPHA',
    },
  ],
}

export const patternLearningContent = {
  strapline: 'Un snapshot capture l etat exact, puis un rewind restaure cet etat sans exposer l interieur de l objet.',
  intuition:
    'Memento est utile quand tu veux revenir proprement a un etat precedent sans casser l encapsulation. L objet metier capture son etat dans un snapshot, un caretaker le conserve, puis l objet peut se restaurer plus tard.',
  readingGuide:
    'Regarde d abord l etat live de la scene, puis les checkpoints sauvegardes au centre. Lance la demo pour voir la mutation critique, puis observe si la restauration revient exactement au snapshot ou seulement a une approximation.',
  studentAngle:
    'Le declic pedagogique est de voir qu un historique ne devrait pas forcer le client a connaitre tous les champs internes d un objet.',
  developerAngle:
    'Memento marche bien pour les éditeurs, les jeux, les savepoints et certains historiques undo. Il devient plus delicat quand les snapshots sont lourds ou trop nombreux.',
  playfulPrompt:
    'Compare avec et sans Memento, puis regarde si l energie, les couches et les annotations reviennent vraiment au checkpoint choisi.',
  steps: [
    'L originator expose un etat courant modifiable.',
    'Le caretaker stocke un snapshot a chaque savepoint important.',
    'Une mutation critique pousse la scene dans un etat degrade.',
    'La restauration recharge un ancien snapshot pour revenir en arriere.',
  ],
  glossary: [
    {
      term: 'Originator',
      definition: 'Objet qui sait capturer et restaurer son propre etat.',
    },
    {
      term: 'Caretaker',
      definition: 'Objet qui range les snapshots sans connaitre leur structure interne.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1200 720',
  classes: [
    {
      id: 'client',
      x: 70,
      y: 280,
      width: 220,
      height: 118,
      title: 'EditorClient',
      stereotype: 'Client',
      methods: ['+ edit()', '+ save()', '+ restore()'],
      tone: 'teal',
    },
    {
      id: 'originator',
      x: 380,
      y: 144,
      width: 308,
      height: 190,
      title: 'SceneOriginator',
      stereotype: 'Originator',
      fields: ['- theme', '- energy', '- layers', '- annotations'],
      methods: ['+ createMemento()', '+ restore(memento)'],
      tone: 'accent',
    },
    {
      id: 'memento',
      x: 820,
      y: 144,
      width: 246,
      height: 150,
      title: 'SceneMemento',
      stereotype: 'Memento',
      fields: ['- stateSnapshot'],
      methods: ['+ state()'],
      tone: 'sand',
    },
    {
      id: 'caretaker',
      x: 760,
      y: 430,
      width: 286,
      height: 134,
      title: 'SnapshotCaretaker',
      stereotype: 'Caretaker',
      fields: ['- history: List<SceneMemento>'],
      methods: ['+ push()', '+ get(code)'],
      tone: 'teal',
    },
  ],
  relations: [
    { from: 'client', to: 'originator', label: 'edits / restore', marker: 'arrow' },
    { from: 'originator', to: 'memento', label: 'creates', marker: 'arrow' },
    { from: 'caretaker', to: 'memento', label: 'stores', marker: 'arrow' },
    { from: 'client', to: 'caretaker', label: 'asks checkpoint', marker: 'arrow' },
  ],
}

export const fallbackQuiz = {
  patternCode: 'memento',
  title: 'Quiz Memento',
  description: 'Teste ta comprehension des snapshots, de la restauration et du role du caretaker.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'memento-q1',
      label: 'Le pattern Memento sert surtout a :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Il capture un etat pour pouvoir le restaurer plus tard.',
      choices: [
        { id: 'restore', label: 'Sauvegarder puis restaurer un etat' },
        { id: 'notify', label: 'Notifier plusieurs abonnes' },
        { id: 'share', label: 'Partager la memoire entre objets' },
      ],
      correctChoiceIds: ['restore'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q2',
      label: 'Le client devrait modifier directement le contenu interne d un memento.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Non : le but est justement de proteger l encapsulation de l originator.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['false'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q3',
      label: 'Memento appartient a la famille :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'C est un pattern comportemental.',
      choices: [
        { id: 'creational', label: 'Création' },
        { id: 'structural', label: 'Structurel' },
        { id: 'behavioral', label: 'Comportemental' },
      ],
      correctChoiceIds: ['behavioral'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q4',
      label: 'Le caretaker a pour role principal de :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le caretaker stocke les snapshots sans connaitre leur structure interne.',
      choices: [
        { id: 'store', label: 'Conserver les snapshots' },
        { id: 'mutate', label: 'Modifier directement l originator' },
        { id: 'parse', label: 'Interpreter un langage' },
      ],
      correctChoiceIds: ['store'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q5',
      label: 'Associe chaque role du pattern Memento a sa responsabilite.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'L originator cree et restaure, le memento capture, le caretaker stocke.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'originator', label: 'Originator' },
        { id: 'memento', label: 'Memento' },
        { id: 'caretaker', label: 'Caretaker' },
      ],
      rightItems: [
        { id: 'state', label: 'Contient une capture d etat' },
        { id: 'store', label: 'Range les snapshots' },
        { id: 'restore', label: 'Cree et restaure l etat' },
      ],
      correctPairs: [
        { leftId: 'originator', rightId: 'restore' },
        { leftId: 'memento', rightId: 'state' },
        { leftId: 'caretaker', rightId: 'store' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q6',
      label: 'Memento evite surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Il evite de casser l encapsulation juste pour faire undo / restore.',
      choices: [
        { id: 'encapsulation', label: 'Casser l encapsulation pour restaurer un etat' },
        { id: 'inheritance', label: 'Utiliser l heritage' },
        { id: 'network', label: 'Faire des appels reseau' },
      ],
      correctChoiceIds: ['encapsulation'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q7',
      label: 'On peut s appuyer sur Memento pour construire un historique undo / redo.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : une pile de snapshots est un cas d usage classique.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q8',
      label: 'Quel exemple illustre bien Memento ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Un éditeur ou un jeu avec savepoints est un excellent exemple.',
      choices: [
        { id: 'savepoint', label: 'Un jeu avec savepoints ou rewind' },
        { id: 'factory', label: 'Une fabrique de vehicules' },
        { id: 'observer', label: 'Un systeme pub/sub' },
      ],
      correctChoiceIds: ['savepoint'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q9',
      label: 'Le snapshot doit idealement contenir :',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'L etat necessaire a une restauration coherente, pas seulement quelques notes visibles.',
      choices: [
        { id: 'full', label: 'L etat necessaire a une restauration coherente' },
        { id: 'partial', label: 'Seulement un titre et une date' },
        { id: 'none', label: 'Aucun etat, seulement un identifiant' },
      ],
      correctChoiceIds: ['full'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'memento-q10',
      label: 'Quel risque apparait si on accumule des mementos volumineux sans limite ?',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le pattern peut devenir couteux en memoire si on garde trop de snapshots lourds.',
      choices: [
        { id: 'memory', label: 'Un cout memoire important' },
        { id: 'observer', label: 'Un couplage pub/sub' },
        { id: 'factory', label: 'Une creation trop centralisee' },
      ],
      correctChoiceIds: ['memory'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
  ],
}
