export const patternCode = 'abstract-factory'

export const patternDefinition = {
  code: 'abstract-factory',
  name: 'Abstract Factory',
  type: 'CREATIONAL',
  description:
    'Fabrique des familles d’objets cohérentes sans exposer les classes concrètes ni mélanger les thèmes au niveau du client.',
  useCase:
    'Choisir un thème sci-fi ou médiéval puis générer un héros, un transport et une relique parfaitement alignés.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_ABSTRACT_FACTORY', 'WITHOUT_ABSTRACT_FACTORY'],
      defaultValue: 'WITH_ABSTRACT_FACTORY',
    },
    {
      name: 'themeCode',
      label: 'Thème',
      type: 'SELECT',
      required: true,
      allowedValues: ['SCI_FI', 'MEDIEVAL'],
      defaultValue: 'SCI_FI',
    },
    {
      name: 'generatorLabel',
      label: 'Nom du générateur',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Générateur de thème',
    },
  ],
}

export const patternLearningContent = {
  strapline:
    'Le client choisit une famille complète, pas trois classes concrètes séparées.',
  intuition:
    "Abstract Factory étend l'idée de Factory Method à plusieurs produits qui doivent rester cohérents ensemble. Ici, un thème génère un héros, un transport et une relique sans mélange accidentel entre univers.",
  readingGuide:
    "Regarde d'abord le thème choisi, puis observe comment la famille complète se construit. La scène montre si la cohérence passe par une vraie factory de famille ou par un assemblage manuel fragile.",
  studentAngle:
    "Le point clé est de comprendre que le pattern protège une relation entre produits. Il ne crée pas seulement plus vite : il évite les combinaisons incohérentes.",
  developerAngle:
    'Ce pattern devient utile quand plusieurs objets concrets doivent changer ensemble : thèmes UI, kits de composants, drivers multiplateformes, environnements de jeu ou suites de services.',
  playfulPrompt:
    'Bascule entre Sci-Fi et Médiéval puis coupe la factory pour voir comment un seul objet hors thème casse tout le rendu final.',
  steps: [
    'Le client choisit une famille abstraite.',
    'La concrete factory correspondante est sélectionnée.',
    'Chaque produit concret est créé dans le même univers.',
    'Le client récupère une famille cohérente sans connaître les classes concrètes.',
  ],
  glossary: [
    {
      term: 'Abstract Factory',
      definition: 'Contrat qui déclare la création de plusieurs produits reliés.',
    },
    {
      term: 'Product Family',
      definition: 'Ensemble d’objets concrets qui doivent rester compatibles ou cohérents ensemble.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1160 760',
  classes: [
    {
      id: 'client',
      x: 60,
      y: 300,
      width: 230,
      height: 112,
      title: 'ThemeGeneratorClient',
      stereotype: 'Client',
      methods: ['+ buildScene(factory)', '+ previewTheme()'],
      tone: 'teal',
    },
    {
      id: 'abstractFactory',
      x: 342,
      y: 78,
      width: 290,
      height: 176,
      title: 'ThemeFactory',
      stereotype: 'Abstract Factory',
      methods: ['+ createHero()', '+ createTransport()', '+ createRelic()'],
      tone: 'accent',
    },
    {
      id: 'medievalFactory',
      x: 300,
      y: 468,
      width: 240,
      height: 122,
      title: 'MedievalThemeFactory',
      stereotype: 'Concrete Factory',
      methods: ['+ createHero()', '+ createTransport()'],
      tone: 'sand',
    },
    {
      id: 'scifiFactory',
      x: 576,
      y: 468,
      width: 220,
      height: 122,
      title: 'SciFiThemeFactory',
      stereotype: 'Concrete Factory',
      methods: ['+ createHero()', '+ createTransport()'],
      tone: 'sand',
    },
    {
      id: 'hero',
      x: 760,
      y: 66,
      width: 290,
      height: 122,
      title: 'ThemeHero',
      stereotype: 'Abstract Product',
      methods: ['+ label()', '+ detail()'],
      tone: 'teal',
    },
    {
      id: 'transport',
      x: 760,
      y: 260,
      width: 290,
      height: 122,
      title: 'ThemeTransport',
      stereotype: 'Abstract Product',
      methods: ['+ label()', '+ detail()'],
      tone: 'teal',
    },
    {
      id: 'relic',
      x: 760,
      y: 454,
      width: 290,
      height: 122,
      title: 'ThemeRelic',
      stereotype: 'Abstract Product',
      methods: ['+ label()', '+ detail()'],
      tone: 'teal',
    },
  ],
  relations: [
    { from: 'client', to: 'abstractFactory', label: 'uses', marker: 'arrow' },
    { from: 'medievalFactory', to: 'abstractFactory', label: 'implements', marker: 'triangle', dashed: true },
    { from: 'scifiFactory', to: 'abstractFactory', label: 'implements', marker: 'triangle', dashed: true },
    { from: 'abstractFactory', to: 'hero', label: 'createHero()', marker: 'arrow' },
    { from: 'abstractFactory', to: 'transport', label: 'createTransport()', marker: 'arrow' },
    { from: 'abstractFactory', to: 'relic', label: 'createRelic()', marker: 'arrow' },
  ],
}

export const fallbackQuiz = {
  patternCode: 'abstract-factory',
  title: 'Quiz Abstract Factory',
  description: 'Teste ta compréhension de la création de familles d’objets cohérentes.',
  passingPercent: 75,
  badgeLabel: 'Badge validé',
  maxPoints: 0,
  questions: [
    {
      id: 'abstract-factory-q1',
      label: 'Abstract Factory sert surtout à :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Le pattern crée plusieurs produits coordonnés dans une même famille.',
      choices: [
        { id: 'family', label: 'Créer des familles d’objets cohérentes' },
        { id: 'undo', label: 'Restaurer un snapshot' },
        { id: 'notify', label: 'Notifier plusieurs observers' },
      ],
      correctChoiceIds: ['family'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q2',
      label: 'Abstract Factory appartient aux patterns de création.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : il organise la création de plusieurs produits reliés.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q3',
      label: 'Par rapport à Factory Method, Abstract Factory ajoute surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: "Il fabrique une famille complète plutôt qu'un seul produit.",
      choices: [
        { id: 'family', label: 'La création de plusieurs produits reliés' },
        { id: 'singleton', label: 'Une seule instance globale' },
        { id: 'visitor', label: 'Un parcours sur une structure' },
      ],
      correctChoiceIds: ['family'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q4',
      label: 'Dans un générateur de thème, la factory abstraite garantit :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Tous les objets doivent rester dans le même univers visuel.',
      choices: [
        { id: 'coherent', label: 'Une cohérence entre héros, transport et relique' },
        { id: 'faster', label: 'Une exécution plus rapide' },
        { id: 'cache', label: 'Un partage mémoire' },
      ],
      correctChoiceIds: ['coherent'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q5',
      label: 'Associe chaque élément à son rôle dans Abstract Factory.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le contrat déclare, la factory concrète choisit le thème, et la famille fournit les objets.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'abstractFactory', label: 'Abstract Factory' },
        { id: 'concreteFactory', label: 'Concrete Factory' },
        { id: 'productFamily', label: 'Concrete Products' },
      ],
      rightItems: [
        { id: 'contract', label: 'Déclare createHero(), createTransport(), createRelic()' },
        { id: 'theme', label: 'Choisit Sci-Fi ou Médiéval' },
        { id: 'objects', label: 'Fournit les objets concrets du thème' },
      ],
      correctPairs: [
        { leftId: 'abstractFactory', rightId: 'contract' },
        { leftId: 'concreteFactory', rightId: 'theme' },
        { leftId: 'productFamily', rightId: 'objects' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q6',
      label: 'Quel risque évitons-nous sans Abstract Factory ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Le client peut sinon composer une famille incohérente.',
      choices: [
        { id: 'mix', label: 'Mélanger des produits de thèmes différents' },
        { id: 'network', label: 'Perdre la connexion réseau' },
        { id: 'cursor', label: "Perdre la position d'un iterator" },
      ],
      correctChoiceIds: ['mix'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q7',
      label: 'Le client devrait connaître directement les classes concrètes de chaque produit.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Faux : elles restent cachées derrière le contrat de factory.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['false'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q8',
      label: 'Quel exemple illustre bien Abstract Factory ?',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le générateur de thème est un bon exemple car plusieurs produits doivent rester alignés.',
      choices: [
        { id: 'theme', label: 'Un générateur Sci-Fi / Médiéval qui crée plusieurs objets assortis' },
        { id: 'undo', label: 'Un historique de sauvegardes' },
        { id: 'pubsub', label: 'Un sujet qui pousse des notifications' },
      ],
      correctChoiceIds: ['theme'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q9',
      label: 'Quel couple est le plus suspect sans Abstract Factory ?',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le mélange de familles concrètes est le vrai problème.',
      choices: [
        { id: 'mismatch', label: 'Knight Champion + Hoverbike futuriste dans la même famille médiévale' },
        { id: 'same', label: 'Nova Pilot + Hoverbike dans le même thème sci-fi' },
        { id: 'stable', label: 'Runic Banner + Warhorse dans le même thème médiéval' },
      ],
      correctChoiceIds: ['mismatch'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q10',
      label: 'Remets le flux Abstract Factory dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client choisit un thème, la factory concrète est sélectionnée, puis la famille est générée et livrée.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'choose', label: 'Le client choisit un thème' },
        { id: 'factory', label: 'La factory concrète correspondante est sélectionnée' },
        { id: 'products', label: 'Les produits cohérents sont créés' },
        { id: 'result', label: 'La famille finale est livrée au client' },
      ],
      correctOrder: ['choose', 'factory', 'products', 'result'],
    },
  ],
}
