export const patternCode = 'abstract-factory'

export const patternDefinition = {
  code: 'abstract-factory',
  name: 'Abstract Factory',
  type: 'CREATIONAL',
  description:
    'Fabrique des familles d objets coherentes sans exposer les classes concretes ni melanger les themes au niveau du client.',
  useCase:
    'Choisir un theme sci-fi ou medieval puis generer un hero, un transport et une relique parfaitement alignes.',
  complexityLevel: 'INTERMEDIATE',
}

export const fallbackSchema = {
  fields: [
    {
      name: 'mode',
      label: 'Mode',
      type: 'SELECT',
      required: true,
      allowedValues: ['WITH_ABSTRACT_FACTORY', 'WITHOUT_ABSTRACT_FACTORY'],
      defaultValue: 'WITH_ABSTRACT_FACTORY',
    },
    {
      name: 'themeCode',
      label: 'Theme',
      type: 'SELECT',
      required: true,
      allowedValues: ['SCI_FI', 'MEDIEVAL'],
      defaultValue: 'SCI_FI',
    },
    {
      name: 'generatorLabel',
      label: 'Nom du generateur',
      type: 'TEXT',
      required: true,
      allowedValues: null,
      defaultValue: 'Theme Generator',
    },
  ],
}

export const patternLearningContent = {
  strapline:
    'Le client choisit une famille complete, pas trois classes concretes separees.',
  intuition:
    'Abstract Factory etend l idee de Factory Method a plusieurs produits qui doivent rester coherents ensemble. Ici, un theme genere un hero, un transport et une relique sans melange accidentel entre univers.',
  readingGuide:
    'Regarde d abord le theme choisi, puis observe comment la famille complete se construit. La scene montre si la coherence passe par une vraie factory de famille ou par un assemblage manuel fragile.',
  studentAngle:
    'Le point cle est de comprendre que le pattern protege une relation entre produits. Il ne cree pas seulement plus vite : il evite les combinaisons incoherentes.',
  developerAngle:
    'Ce pattern devient utile quand plusieurs objets concrets doivent changer ensemble : themes UI, kits de composants, drivers multiplateformes, environnements de jeu ou suites de services.',
  playfulPrompt:
    'Bascule entre Sci-Fi et Medieval puis coupe la factory pour voir comment un seul objet hors theme casse tout le rendu final.',
  steps: [
    'Le client choisit une famille abstraite.',
    'La concrete factory correspondante est selectionnee.',
    'Chaque produit concret est cree dans le meme univers.',
    'Le client recupere une famille coherente sans connaitre les classes concretes.',
  ],
  glossary: [
    {
      term: 'Abstract Factory',
      definition: 'Contrat qui declare la creation de plusieurs produits relies.',
    },
    {
      term: 'Product Family',
      definition: 'Ensemble d objets concrets qui doivent rester compatibles ou coherents ensemble.',
    },
  ],
}

export const patternUmlDiagram = {
  viewBox: '0 0 1160 760',
  classes: [
    {
      id: 'client',
      x: 60,
      y: 300,
      width: 230,
      height: 112,
      title: 'ThemeGeneratorClient',
      stereotype: 'Client',
      methods: ['+ buildScene(factory)', '+ previewTheme()'],
      tone: 'teal',
    },
    {
      id: 'abstractFactory',
      x: 342,
      y: 78,
      width: 290,
      height: 176,
      title: 'ThemeFactory',
      stereotype: 'Abstract Factory',
      methods: ['+ createHero()', '+ createTransport()', '+ createRelic()'],
      tone: 'accent',
    },
    {
      id: 'medievalFactory',
      x: 300,
      y: 468,
      width: 240,
      height: 122,
      title: 'MedievalThemeFactory',
      stereotype: 'Concrete Factory',
      methods: ['+ createHero()', '+ createTransport()'],
      tone: 'sand',
    },
    {
      id: 'scifiFactory',
      x: 576,
      y: 468,
      width: 220,
      height: 122,
      title: 'SciFiThemeFactory',
      stereotype: 'Concrete Factory',
      methods: ['+ createHero()', '+ createTransport()'],
      tone: 'sand',
    },
    {
      id: 'hero',
      x: 760,
      y: 66,
      width: 290,
      height: 122,
      title: 'ThemeHero',
      stereotype: 'Abstract Product',
      methods: ['+ label()', '+ detail()'],
      tone: 'teal',
    },
    {
      id: 'transport',
      x: 760,
      y: 260,
      width: 290,
      height: 122,
      title: 'ThemeTransport',
      stereotype: 'Abstract Product',
      methods: ['+ label()', '+ detail()'],
      tone: 'teal',
    },
    {
      id: 'relic',
      x: 760,
      y: 454,
      width: 290,
      height: 122,
      title: 'ThemeRelic',
      stereotype: 'Abstract Product',
      methods: ['+ label()', '+ detail()'],
      tone: 'teal',
    },
  ],
  relations: [
    { from: 'client', to: 'abstractFactory', label: 'uses', marker: 'arrow' },
    { from: 'medievalFactory', to: 'abstractFactory', label: 'implements', marker: 'triangle', dashed: true },
    { from: 'scifiFactory', to: 'abstractFactory', label: 'implements', marker: 'triangle', dashed: true },
    { from: 'abstractFactory', to: 'hero', label: 'createHero()', marker: 'arrow' },
    { from: 'abstractFactory', to: 'transport', label: 'createTransport()', marker: 'arrow' },
    { from: 'abstractFactory', to: 'relic', label: 'createRelic()', marker: 'arrow' },
  ],
}

export const fallbackQuiz = {
  patternCode: 'abstract-factory',
  title: 'Quiz Abstract Factory',
  description: 'Teste ta comprehension de la creation de familles d objets coherentes.',
  passingPercent: 75,
  badgeLabel: 'Badge valide',
  maxPoints: 0,
  questions: [
    {
      id: 'abstract-factory-q1',
      label: 'Abstract Factory sert surtout a :',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Le pattern cree plusieurs produits coordonnes dans une meme famille.',
      choices: [
        { id: 'family', label: 'Creer des familles d objets coherentes' },
        { id: 'undo', label: 'Restaurer un snapshot' },
        { id: 'notify', label: 'Notifier plusieurs observers' },
      ],
      correctChoiceIds: ['family'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q2',
      label: 'Abstract Factory appartient aux patterns de creation.',
      type: 'TRUE_FALSE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Oui : il organise la creation de plusieurs produits relies.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['true'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q3',
      label: 'Par rapport a Factory Method, Abstract Factory ajoute surtout :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Il fabrique une famille complete plutot qu un seul produit.',
      choices: [
        { id: 'family', label: 'La creation de plusieurs produits relies' },
        { id: 'singleton', label: 'Une seule instance globale' },
        { id: 'visitor', label: 'Un parcours sur une structure' },
      ],
      correctChoiceIds: ['family'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q4',
      label: 'Dans un Theme Generator, la factory abstraite garantit :',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Tous les objets doivent rester dans le meme univers visuel.',
      choices: [
        { id: 'coherent', label: 'Une coherence entre hero, transport et relique' },
        { id: 'faster', label: 'Une execution plus rapide' },
        { id: 'cache', label: 'Un partage memoire' },
      ],
      correctChoiceIds: ['coherent'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q5',
      label: 'Associe chaque element a son role dans Abstract Factory.',
      type: 'MATCHING',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le contrat declare, la factory concrete choisit le theme, et la famille fournit les objets.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [
        { id: 'abstractFactory', label: 'Abstract Factory' },
        { id: 'concreteFactory', label: 'Concrete Factory' },
        { id: 'productFamily', label: 'Concrete Products' },
      ],
      rightItems: [
        { id: 'contract', label: 'Declare createHero(), createTransport(), createRelic()' },
        { id: 'theme', label: 'Choisit Sci-Fi ou Medieval' },
        { id: 'objects', label: 'Fournit les objets concrets du theme' },
      ],
      correctPairs: [
        { leftId: 'abstractFactory', rightId: 'contract' },
        { leftId: 'concreteFactory', rightId: 'theme' },
        { leftId: 'productFamily', rightId: 'objects' },
      ],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q6',
      label: 'Quel risque evitons-nous sans Abstract Factory ?',
      type: 'QCM_SINGLE',
      difficulty: 'EASY',
      points: 0,
      explanation: 'Le client peut sinon composer une famille incoherente.',
      choices: [
        { id: 'mix', label: 'Melanger des produits de themes differents' },
        { id: 'network', label: 'Perdre la connexion reseau' },
        { id: 'cursor', label: 'Perdre la position d un iterator' },
      ],
      correctChoiceIds: ['mix'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q7',
      label: 'Le client devrait connaitre directement les classes concretes de chaque produit.',
      type: 'TRUE_FALSE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Faux : elles restent cachees derriere le contrat de factory.',
      choices: [{ id: 'true', label: 'Vrai' }, { id: 'false', label: 'Faux' }],
      correctChoiceIds: ['false'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q8',
      label: 'Quel exemple illustre bien Abstract Factory ?',
      type: 'QCM_SINGLE',
      difficulty: 'MEDIUM',
      points: 0,
      explanation: 'Le generateur de theme est un bon exemple car plusieurs produits doivent rester alignes.',
      choices: [
        { id: 'theme', label: 'Un generateur Sci-Fi / Medieval qui cree plusieurs objets assortis' },
        { id: 'undo', label: 'Un historique de sauvegardes' },
        { id: 'pubsub', label: 'Un sujet qui pousse des notifications' },
      ],
      correctChoiceIds: ['theme'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q9',
      label: 'Quel couple est le plus suspect sans Abstract Factory ?',
      type: 'QCM_SINGLE',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le melange de familles concretes est le vrai probleme.',
      choices: [
        { id: 'mismatch', label: 'Knight Champion + Hoverbike futuriste dans la meme famille medievale' },
        { id: 'same', label: 'Nova Pilot + Hoverbike dans le meme theme sci-fi' },
        { id: 'stable', label: 'Runic Banner + Warhorse dans le meme theme medieval' },
      ],
      correctChoiceIds: ['mismatch'],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [],
      correctOrder: [],
    },
    {
      id: 'abstract-factory-q10',
      label: 'Remets le flux Abstract Factory dans le bon ordre.',
      type: 'ORDERING',
      difficulty: 'HARD',
      points: 0,
      explanation: 'Le client choisit un theme, la factory concrete est selectionnee, puis la famille est generee et livree.',
      choices: [],
      correctChoiceIds: [],
      leftItems: [],
      rightItems: [],
      correctPairs: [],
      orderingItems: [
        { id: 'choose', label: 'Le client choisit un theme' },
        { id: 'factory', label: 'La factory concrete correspondante est selectionnee' },
        { id: 'products', label: 'Les produits coherents sont crees' },
        { id: 'result', label: 'La famille finale est livree au client' },
      ],
      correctOrder: ['choose', 'factory', 'products', 'result'],
    },
  ],
}
